"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { assignmentApi, type Assignment, type AssignmentCell, type AssignmentSnapshot } from "@/lib/assignment-api";
import { setupApi, type SetupSnapshot } from "@/lib/setup-api";

const statusLabel={missing:"ناقص بالكامل",partial:"ناقص جزئي",complete:"مكتمل",over:"زائد",no_requirement:"لا يوجد مطلوب"};
const value=(item:unknown)=>String(item??"");

export function AssignmentWorkspace(){
  const [schoolId,setSchoolId]=useState("");const [setup,setSetup]=useState<SetupSnapshot|null>(null);const [termId,setTermId]=useState("");const [data,setData]=useState<AssignmentSnapshot|null>(null);
  const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [message,setMessage]=useState("");const [view,setView]=useState<"matrix"|"list">("matrix");
  const [setupOpen,setSetupOpen]=useState(false);const [editor,setEditor]=useState<{cell:AssignmentCell;assignment?:Assignment}|null>(null);const [deleting,setDeleting]=useState<Assignment|null>(null);
  const [selectedCells,setSelectedCells]=useState<string[]>([]);const [bulkOpen,setBulkOpen]=useState(false);const [selectedAssignments,setSelectedAssignments]=useState<string[]>([]);const [listBulk,setListBulk]=useState<"teachers"|"delete"|null>(null);const [busy,setBusy]=useState(false);
  const [search,setSearch]=useState("");const [stage,setStage]=useState("");const [grade,setGrade]=useState("");const [shift,setShift]=useState("");const [subjectFilter,setSubjectFilter]=useState("");const [status,setStatus]=useState("");

  const loadTerm=useCallback(async(school:string,term:string)=>{setLoading(true);try{setData(await assignmentApi.snapshot(school,term));setError("")}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[]);
  const bootstrap=useCallback(async(id?:string)=>{const school=id??localStorage.getItem("pm-school")??"";if(!school){setLoading(false);return}setSchoolId(school);setLoading(true);try{const base=await setupApi.snapshot(school);setSetup(base);const current=base.years.find(y=>y.is_current);const next=value(base.terms.find(t=>t.academic_year_id===current?.id)?.id??base.terms[0]?.id);setTermId(next);if(next)await loadTerm(school,next);else setLoading(false)}catch(e){setError((e as Error).message);setLoading(false)}},[loadTerm]);
  useEffect(()=>{const timer=setTimeout(()=>void bootstrap(),0);const handler=(e:Event)=>void bootstrap((e as CustomEvent<string>).detail);window.addEventListener("pm-school-change",handler);return()=>{clearTimeout(timer);window.removeEventListener("pm-school-change",handler)}},[bootstrap]);
  async function chooseTerm(id:string){setTermId(id);setSelectedCells([]);await loadTerm(schoolId,id)}
  const sectionById=useMemo(()=>new Map(data?.sections.map(item=>[item.id,item])??[]),[data]);const offeringById=useMemo(()=>new Map(data?.offerings.map(item=>[item.id,item])??[]),[data]);
  const teacherById=useMemo(()=>new Map(data?.teachers.map(item=>[item.id,item])??[]),[data]);const subjectById=useMemo(()=>new Map(data?.subjects.map(item=>[item.id,item])??[]),[data]);const resourceById=useMemo(()=>new Map(data?.resources.map(item=>[item.id,item])??[]),[data]);
  const activeOfferings=useMemo(()=>data?.offerings.filter(o=>o.is_active).filter(o=>{const s=sectionById.get(value(o.section_id));return s&&(!search||`${s.stage_name} ${s.grade_name} ${s.name_ar}`.includes(search))&&(!stage||s.stage_id===stage)&&(!grade||s.grade_id===grade)&&(!shift||o.shift_id===shift)})??[],[data,sectionById,search,stage,grade,shift]);
  const subjects=useMemo(()=>data?.subjects.filter(s=>!subjectFilter||s.id===subjectFilter)??[],[data,subjectFilter]);
  function cell(offering:string,subject:string){return data?.cells.find(c=>c.offering_id===offering&&c.subject_id===subject)}
  function assignmentNames(item:Assignment){return {teachers:item.teacher_ids.map(id=>teacherById.get(id)?.name_ar??"—").join("، "),sections:item.section_offering_ids.map(id=>{const o=offeringById.get(id);const s=o?sectionById.get(value(o.section_id)):null;return s?`${s.grade_name} / ${s.name_ar}`:"—"}).join("، "),resources:item.resource_ids.map(id=>resourceById.get(id)?.name_ar??"—").join("، ")}}
  function toggleCell(c:AssignmentCell){const key=`${c.subject_id}:${c.offering_id}`;setSelectedCells(old=>old.includes(key)?old.filter(x=>x!==key):old.length&&old[0].split(":")[0]!==c.subject_id?[key]:[...old,key])}
  async function saveOffering(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const rows=data?.sections.flatMap(section=>{const active=form.get(`active-${section.id}`)==="on";const existing=data.offerings.find(o=>o.section_id===section.id);const shiftId=value(form.get(`shift-${section.id}`)||existing?.shift_id);return shiftId&&(active||existing)?[{term_id:termId,section_id:section.id,shift_id:shiftId,is_active:active}]:[]})??[];if(!rows.length){setError("اختر شعبة واحدة على الأقل وحدد شفتها.");return}setBusy(true);try{await assignmentApi.offerings(schoolId,{offerings:rows});setSetupOpen(false);setMessage("تم حفظ شعب الفصل الدراسي");await loadTerm(schoolId,termId)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function saveAssignment(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editor)return;const form=new FormData(e.currentTarget);const teacherIds=form.getAll("teachers").map(value);const resourceIds=form.getAll("resources").map(value);const offeringIds=form.getAll("sections").map(value);const payload={term_id:termId,subject_id:editor.cell.subject_id,weekly_occurrences:Number(form.get("count")),teacher_ids:teacherIds,section_offering_ids:offeringIds,resource_ids:resourceIds,notes:value(form.get("notes"))||null};setBusy(true);try{const result=editor.assignment?await assignmentApi.update(schoolId,editor.assignment.id,payload):await assignmentApi.create(schoolId,payload);setMessage(result.warnings.length?`تم الحفظ مع ${result.warnings.length} تنبيه تخطيطي`:("تم حفظ الإسناد"));setEditor(null);await loadTerm(schoolId,termId)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function bulkAssign(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget),teacher=value(form.get("teacher"));const offeringIds=selectedCells.map(x=>x.split(":")[1]),subjectId=selectedCells[0]?.split(":")[0];setBusy(true);try{await assignmentApi.bulk(schoolId,{term_id:termId,subject_id:subjectId,section_offering_ids:offeringIds,teacher_ids:[teacher],resource_ids:[],fill_from_curriculum:form.get("fill")==="on",weekly_occurrences:Number(form.get("count"))||null});setMessage(`تم تطبيق الإسناد على ${offeringIds.length} شعبة`);setBulkOpen(false);setSelectedCells([]);await loadTerm(schoolId,termId)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function applyListBulk(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);try{if(listBulk==="teachers")await assignmentApi.bulkTeachers(schoolId,{term_id:termId,assignment_ids:selectedAssignments,teacher_ids:[value(form.get("teacher"))]});else await assignmentApi.bulkDelete(schoolId,{term_id:termId,assignment_ids:selectedAssignments});setMessage(`تم تحديث ${selectedAssignments.length} إسناد`);setSelectedAssignments([]);setListBulk(null);await loadTerm(schoolId,termId)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  if(loading)return <section className="content"><div className="skeleton" aria-label="جار تحميل الإسنادات"/></section>;
  return <section className="content assignment-page"><div className="page-heading"><div><span className="eyebrow">{data?.school.name_ar}</span><h1>إسناد المعلمين</h1><p>اربط الشعب بالمواد والمعلمين للفصل الدراسي المختار.</p></div><div className="heading-actions"><button className="secondary" onClick={()=>setSetupOpen(true)}>شُعب الفصل الدراسي</button><button className={view==="matrix"?"primary":"secondary"} onClick={()=>setView("matrix")}>المصفوفة</button><button className={view==="list"?"primary":"secondary"} onClick={()=>setView("list")}>قائمة الإسنادات</button></div></div>
    {message&&<div className="success-banner" role="status">✓ {message}</div>}{error&&<div className="error-banner" role="alert">{error}</div>}
    <div className="term-bar"><label>العام الدراسي<select value={value(data?.selected_term.academic_year_id)} onChange={e=>{const first=setup?.terms.find(t=>t.academic_year_id===e.target.value);if(first)void chooseTerm(value(first.id))}}>{setup?.years.map(y=><option key={y.id} value={y.id}>{value(y.name)}</option>)}</select></label><label>الفصل الدراسي<select aria-label="الفصل الدراسي" value={termId} onChange={e=>void chooseTerm(e.target.value)}>{setup?.terms.filter(t=>t.academic_year_id===data?.selected_term.academic_year_id).map(t=><option key={t.id} value={t.id}>{value(t.name_ar)}</option>)}</select></label><strong>لا تُخلط إسنادات الفصول الدراسية</strong></div>
    {view==="matrix"&&<><div className="assignment-filters"><label>بحث<input aria-label="بحث الشعب" value={search} onChange={e=>setSearch(e.target.value)} placeholder="المرحلة أو الصف أو الشعبة"/></label><label>المرحلة<select value={stage} onChange={e=>setStage(e.target.value)}><option value="">الكل</option>{[...new Map(data?.sections.map(s=>[s.stage_id,s.stage_name])).entries()].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>الصف<select value={grade} onChange={e=>setGrade(e.target.value)}><option value="">الكل</option>{[...new Map(data?.sections.map(s=>[s.grade_id,s.grade_name])).entries()].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>الشفت<select value={shift} onChange={e=>setShift(e.target.value)}><option value="">الكل</option>{data?.shifts.map(s=><option key={s.id} value={s.id}>{value(s.name_ar)}</option>)}</select></label><label>المادة<select value={subjectFilter} onChange={e=>setSubjectFilter(e.target.value)}><option value="">الكل</option>{data?.subjects.map(s=><option key={s.id} value={s.id}>{value(s.name_ar)}</option>)}</select></label><label>الحالة<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">الكل</option>{Object.entries(statusLabel).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label></div>
      {!activeOfferings.length?<div className="empty-state"><h2>لم تُفعّل شعب لهذا الفصل</h2><p>حدد الشعب والشفت أولًا لبدء الإسناد.</p><button className="primary" onClick={()=>setSetupOpen(true)}>إعداد شعب الفصل</button></div>:<div className="matrix-scroll"><table className="assignment-matrix"><thead><tr><th>الشعبة</th>{subjects.map(s=><th key={s.id}>{value(s.name_ar)}</th>)}</tr></thead><tbody>{activeOfferings.map(o=>{const section=sectionById.get(value(o.section_id));return <tr key={o.id}><th><strong>{section?.grade_name} / {section?.name_ar}</strong><small>{section?.stage_name}</small></th>{subjects.map(subject=>{const c=cell(o.id,subject.id);if(!c||status&&c.status!==status)return <td key={subject.id} className="filtered-cell">—</td>;const groups=c.assignment_ids.map(id=>data?.assignments.find(a=>a.id===id)).filter(Boolean) as Assignment[];return <td key={subject.id} className={`coverage-${c.status}`}><button className="cell-main" onClick={()=>setEditor({cell:c})} aria-label={`إسناد ${value(subject.name_ar)} إلى ${section?.name_ar}`}><span>{c.required??"—"} مطلوب / {c.assigned} مسند</span><b>{statusLabel[c.status]}</b>{groups.length>0&&<small>{[...new Set(groups.flatMap(g=>g.teacher_ids).map(id=>teacherById.get(id)?.name_ar))].join("، ")}</small>}{groups.some(g=>g.resource_ids.length)&&<i>◆ مورد</i>}</button><label className="cell-select"><input type="checkbox" aria-label="اختيار الخلية للإسناد الجماعي" checked={selectedCells.includes(`${c.subject_id}:${c.offering_id}`)} onChange={()=>toggleCell(c)}/></label></td>})}</tr>})}</tbody></table></div>}
      {selectedCells.length>0&&<div className="bulk-bar" role="region" aria-label="إجراءات جماعية"><strong>{selectedCells.length} خلية محددة لنفس المادة</strong><button className="primary" onClick={()=>setBulkOpen(true)}>إسناد جماعي</button><button className="secondary" onClick={()=>setSelectedCells([])}>إلغاء التحديد</button></div>}</>}
    {view==="list"&&<div className="advanced-list"><div className="list-heading"><div><h2>مجموعات التدريس</h2><p>عرض واضح للحصص المدمجة والتدريس المشترك.</p></div>{selectedAssignments.length>0&&<div className="heading-actions"><span>{selectedAssignments.length} محدد</span><button onClick={()=>setListBulk("teachers")}>تغيير المعلم جماعيًا</button><button className="danger-link" onClick={()=>setListBulk("delete")}>حذف المحدد</button></div>}</div>{!data?.assignments.length?<div className="empty-state"><h2>لا توجد إسنادات</h2></div>:data.assignments.map(a=>{const names=assignmentNames(a);return <article key={a.id}><label className="assignment-check"><input type="checkbox" aria-label="اختيار الإسناد" checked={selectedAssignments.includes(a.id)} onChange={()=>setSelectedAssignments(old=>old.includes(a.id)?old.filter(id=>id!==a.id):[...old,a.id])}/></label><div><b>{value(subjectById.get(a.subject_id)?.name_ar)}</b><span>{a.weekly_occurrences} حصص أسبوعيًا</span></div><div><small>الشعب</small><strong>{names.sections}</strong></div><div><small>المعلمون</small><strong>{names.teachers}{a.teacher_ids.length>1?" · تدريس مشترك":""}</strong></div><div><small>الموارد</small><strong>{names.resources||"دون مورد"}</strong></div><div className="row-actions"><button onClick={()=>{const c=data.cells.find(x=>x.assignment_ids.includes(a.id));if(c)setEditor({cell:c,assignment:a})}}>تعديل</button><button className="danger-link" onClick={()=>setDeleting(a)}>حذف</button></div></article>})}</div>}
    {setupOpen&&<div className="dialog-backdrop"><section className="edit-dialog wide-dialog" role="dialog" aria-modal="true" aria-labelledby="offering-title"><div className="dialog-heading"><div><span>الفصل الدراسي المختار</span><h2 id="offering-title">شُعب الفصل الدراسي والشفتات</h2></div><button aria-label="إغلاق" onClick={()=>setSetupOpen(false)}>×</button></div>{data?.shifts.length===1&&<p className="helper-note">يوجد شفت واحد فقط؛ يمكنك تفعيل الشعب واستخدامه مباشرة.</p>}<form onSubmit={saveOffering}><div className="offering-list">{data?.sections.map(section=>{const old=data.offerings.find(o=>o.section_id===section.id);return <div key={section.id}><label className="check-field"><input type="checkbox" name={`active-${section.id}`} defaultChecked={Boolean(old?.is_active)}/>{section.stage_name} · {section.grade_name} / {section.name_ar}</label><select aria-label={`شفت ${section.name_ar}`} name={`shift-${section.id}`} defaultValue={value(old?.shift_id??(data.shifts.length===1?data.shifts[0].id:""))}><option value="">اختر الشفت</option>{data.shifts.map(s=><option key={s.id} value={s.id}>{value(s.name_ar)}</option>)}</select></div>})}</div><div className="dialog-actions"><button type="button" className="secondary" onClick={()=>setSetupOpen(false)}>إلغاء</button><button className="primary" disabled={busy}>حفظ الشعب والشفتات</button></div></form></section></div>}
    {editor&&<div className="drawer-backdrop"><section className="assignment-drawer" role="dialog" aria-modal="true" aria-labelledby="assignment-editor"><div className="dialog-heading"><div><span>{value(subjectById.get(editor.cell.subject_id)?.name_ar)}</span><h2 id="assignment-editor">تحرير الإسناد</h2></div><button aria-label="إغلاق" onClick={()=>setEditor(null)}>×</button></div><div className="coverage-preview"><span>المطلوب {editor.cell.required??"غير محدد"}</span><strong>المسند {editor.cell.assigned}</strong><b>{statusLabel[editor.cell.status]}</b></div>{editor.cell.assignment_ids.length>0&&!editor.assignment&&<div className="existing-groups"><h3>الإسنادات الحالية</h3>{editor.cell.assignment_ids.map(id=>{const a=data?.assignments.find(x=>x.id===id);return a?<button key={id} onClick={()=>setEditor({cell:editor.cell,assignment:a})}>{assignmentNames(a).teachers} · {a.weekly_occurrences} حصص</button>:null})}<button className="secondary" onClick={()=>setEditor({cell:editor.cell})}>إضافة إسناد آخر (تقسيم)</button></div>}<form onSubmit={saveAssignment}><label>عدد الحصص الأسبوعية<input type="number" name="count" min="1" max="60" defaultValue={editor.assignment?.weekly_occurrences??Math.max(1,(editor.cell.required??1)-editor.cell.assigned)} required/></label><fieldset><legend>المعلمون</legend>{data?.teachers.map(t=><label className="choice-row" key={t.id}><input type="checkbox" name="teachers" value={t.id} defaultChecked={editor.assignment?.teacher_ids.includes(t.id)}/><span>{t.name_ar}<small>المسند {t.assigned_workload} / الحد {t.teaching_workload_limit}{t.assigned_workload>t.teaching_workload_limit?" · تجاوز الحد":""}</small></span></label>)}</fieldset><fieldset><legend>الشعب — يمكن دمج أكثر من شعبة</legend>{activeOfferings.map(o=>{const s=sectionById.get(value(o.section_id));return <label className="choice-row" key={o.id}><input type="checkbox" name="sections" value={o.id} defaultChecked={editor.assignment?editor.assignment.section_offering_ids.includes(o.id):o.id===editor.cell.offering_id}/><span>{s?.grade_name} / {s?.name_ar}</span></label>})}</fieldset><fieldset><legend>الغرف والموارد</legend>{data?.resources.map(r=><label className="choice-row" key={r.id}><input type="checkbox" name="resources" value={r.id} defaultChecked={editor.assignment?.resource_ids.includes(r.id)}/><span>{value(r.name_ar)}</span></label>)}</fieldset><label>ملاحظات<textarea name="notes" defaultValue={editor.assignment?.notes??""}/></label><div className="dialog-actions"><button type="button" className="secondary" onClick={()=>setEditor(null)}>إلغاء</button><button className="primary" disabled={busy}>حفظ الإسناد</button></div></form></section></div>}
    {bulkOpen&&<div className="dialog-backdrop"><section className="confirm-dialog" role="dialog" aria-modal="true"><h2>معاينة الإسناد الجماعي</h2><p>سيُنشأ إسناد مستقل لكل واحدة من {selectedCells.length} شعبة في المادة نفسها.</p><form onSubmit={bulkAssign}><label>المعلم<select name="teacher" required><option value="">اختر المعلم</option>{data?.teachers.map(t=><option key={t.id} value={t.id}>{t.name_ar} — {t.assigned_workload}/{t.teaching_workload_limit}{t.other_school_overlapping_workload?` + ${t.other_school_overlapping_workload} في مدارس متزامنة`:""}</option>)}</select></label><label className="check-field"><input type="checkbox" name="fill" defaultChecked/>تعبئة العدد المطلوب من المنهج</label><label>عدد مخصص عند إلغاء التعبئة<input type="number" name="count" min="1"/></label><div className="dialog-actions"><button type="button" className="secondary" onClick={()=>setBulkOpen(false)}>إلغاء</button><button className="primary" disabled={busy}>تطبيق على {selectedCells.length} خلية</button></div></form></section></div>}
    {listBulk&&<div className="dialog-backdrop"><section className="confirm-dialog" role={listBulk==="delete"?"alertdialog":"dialog"} aria-modal="true"><h2>{listBulk==="delete"?"حذف الإسنادات المحددة":"تغيير المعلم جماعيًا"}</h2><p>ستتأثر {selectedAssignments.length} مجموعة تدريس بعد تأكيد العملية.</p><form onSubmit={applyListBulk}>{listBulk==="teachers"&&<label>المعلم البديل<select name="teacher" required><option value="">اختر المعلم</option>{data?.teachers.map(t=><option key={t.id} value={t.id}>{t.name_ar}</option>)}</select></label>}<div className="dialog-actions"><button type="button" className="secondary" onClick={()=>setListBulk(null)}>إلغاء</button><button className={listBulk==="delete"?"danger-button":"primary"} disabled={busy}>تأكيد العملية</button></div></form></section></div>}
    {deleting&&<div className="dialog-backdrop"><section className="confirm-dialog" role="alertdialog" aria-modal="true"><h2>حذف الإسناد</h2><p>سيُحذف إسناد {value(subjectById.get(deleting.subject_id)?.name_ar)} وروابط المعلمين والشعب والموارد التابعة له.</p><div className="dialog-actions"><button className="secondary" onClick={()=>setDeleting(null)}>إلغاء</button><button className="danger-button" onClick={async()=>{setBusy(true);try{await assignmentApi.remove(schoolId,deleting.id);setDeleting(null);setMessage("تم حذف الإسناد");await loadTerm(schoolId,termId)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>تأكيد الحذف</button></div></section></div>}
  </section>;
}
