import { cleanup,fireEvent,render,screen,waitFor } from "@testing-library/react";
import { afterEach,beforeEach,describe,expect,it,vi } from "vitest";
import { assignmentApi, type AssignmentSnapshot } from "@/lib/assignment-api";
import { setupApi } from "@/lib/setup-api";
import { AssignmentWorkspace } from "./assignment-workspace";

const setup={school:{id:"s1",name_ar:"مدرسة النور",code:"S1"},years:[{id:"y1",name:"1448",is_current:true},{id:"y2",name:"1449",is_current:false}],terms:[{id:"term1",academic_year_id:"y1",name_ar:"الفصل الأول"},{id:"term2",academic_year_id:"y1",name_ar:"الفصل الثاني"},{id:"term3",academic_year_id:"y2",name_ar:"الفصل الأول"}],shifts:[],patterns:[],days:[],blocks:[],stages:[],grades:[],sections:[]};
const snapshot={school:setup.school,selected_term:{id:"term1",academic_year_id:"y1",name_ar:"الفصل الأول"},years:setup.years,terms:setup.terms,shifts:[{id:"shift1",name_ar:"صباحي"}],sections:[{id:"sec1",name_ar:"أ",grade_id:"g1",grade_name:"الأول المتوسط",stage_id:"st1",stage_name:"المتوسطة"},{id:"sec2",name_ar:"ب",grade_id:"g1",grade_name:"الأول المتوسط",stage_id:"st1",stage_name:"المتوسطة"}],offerings:[{id:"o1",section_id:"sec1",shift_id:"shift1",term_id:"term1",is_active:true},{id:"o2",section_id:"sec2",shift_id:"shift1",term_id:"term1",is_active:true}],subjects:[{id:"sub1",name_ar:"الرياضيات"},{id:"sub2",name_ar:"العلوم"}],resources:[{id:"r1",name_ar:"مختبر العلوم"}],teachers:[{id:"t1",name_ar:"أحمد",base_workload:18,teaching_workload_limit:4,assigned_workload:5},{id:"t2",name_ar:"علي",base_workload:18,teaching_workload_limit:24,assigned_workload:5}],assignments:[{id:"a1",term_id:"term1",subject_id:"sub1",weekly_occurrences:5,teacher_ids:["t1","t2"],section_offering_ids:["o1","o2"],resource_ids:["r1"],notes:null}],cells:[{offering_id:"o1",subject_id:"sub1",required:6,assigned:5,status:"partial",assignment_ids:["a1"]},{offering_id:"o1",subject_id:"sub2",required:4,assigned:0,status:"missing",assignment_ids:[]},{offering_id:"o2",subject_id:"sub1",required:5,assigned:5,status:"complete",assignment_ids:["a1"]},{offering_id:"o2",subject_id:"sub2",required:4,assigned:5,status:"over",assignment_ids:["a1"]}]};
vi.mock("@/lib/setup-api",()=>({setupApi:{snapshot:vi.fn()},API_URL:"",TENANT_ID:""}));
vi.mock("@/lib/assignment-api",()=>({assignmentApi:{snapshot:vi.fn(),offerings:vi.fn(),create:vi.fn(),update:vi.fn(),remove:vi.fn(),preview:vi.fn(),bulk:vi.fn(),bulkPreview:vi.fn(),bulkTeachers:vi.fn(),bulkDelete:vi.fn()}}));

describe("assignment workspace",()=>{beforeEach(()=>{Object.defineProperty(window,"localStorage",{configurable:true,value:{getItem:()=>"s1"}});vi.mocked(setupApi.snapshot).mockResolvedValue(setup);vi.mocked(assignmentApi.snapshot).mockResolvedValue(snapshot as unknown as AssignmentSnapshot);vi.mocked(assignmentApi.bulk).mockResolvedValue([]);vi.mocked(assignmentApi.bulkPreview).mockResolvedValue({can_apply:true,coverage:[{offering_id:"o1",required:6,current_assigned:4,delta:2,projected_assigned:6,projected_status:"complete",action:"apply"}],teacher_workloads:[{teacher_id:"t1",current_workload:5,delta:2,projected_workload:7,teaching_workload_limit:4,exceeds_limit:true}],warnings:[{code:"teacher_workload_exceeded",teacher_id:"t1",value:7}]});vi.mocked(assignmentApi.preview).mockResolvedValue({can_apply:true,coverage:[{offering_id:"o1",required:6,current_assigned:5,delta:1,projected_assigned:6,projected_status:"complete",action:"apply"}],teacher_workloads:[{teacher_id:"t1",current_workload:5,delta:1,projected_workload:6,teaching_workload_limit:4,exceeds_limit:true}],warnings:[]})});afterEach(()=>{cleanup();vi.clearAllMocks()});
 it("keeps an explicit term selector and reloads the selected term",async()=>{render(<AssignmentWorkspace/>);expect(await screen.findByText("إسناد المعلمين")).toBeInTheDocument();fireEvent.change(screen.getByRole("combobox",{name:"الفصل الدراسي"}),{target:{value:"term2"}});await waitFor(()=>expect(assignmentApi.snapshot).toHaveBeenCalledWith("s1","term2"));expect(screen.getByText("لا تُخلط إسنادات الفصول الدراسية")).toBeInTheDocument()});
 it("configures active sections and explicit shifts",async()=>{vi.mocked(assignmentApi.offerings).mockResolvedValue([]);render(<AssignmentWorkspace/>);await screen.findByText("إسناد المعلمين");fireEvent.click(screen.getByRole("button",{name:"شُعب الفصل الدراسي"}));expect(screen.getByRole("dialog")).toHaveTextContent("شُعب الفصل الدراسي والشفتات");expect(screen.getByRole("combobox",{name:"شفت أ"})).toHaveValue("shift1");fireEvent.click(screen.getByRole("button",{name:"حفظ الشعب والشفتات"}));await waitFor(()=>expect(assignmentApi.offerings).toHaveBeenCalled())});
 it("renders coverage states and opens a multi-teacher resource editor with workload warning",async()=>{render(<AssignmentWorkspace/>);await screen.findByText("إسناد المعلمين");expect(screen.getAllByText("ناقص جزئي").length).toBeGreaterThan(0);expect(screen.getAllByText("مكتمل").length).toBeGreaterThan(0);expect(screen.getAllByText("زائد").length).toBeGreaterThan(0);fireEvent.click(screen.getByRole("button",{name:"إسناد الرياضيات إلى أ"}));expect(screen.getByRole("dialog")).toHaveTextContent("تحرير الإسناد");expect(screen.getByRole("dialog")).toHaveTextContent("تجاوز الحد");expect(screen.getByText("مختبر العلوم")).toBeInTheDocument()});
 it("requires a factual server preview before an individual save",async()=>{render(<AssignmentWorkspace/>);await screen.findByText("إسناد المعلمين");fireEvent.click(screen.getByRole("button",{name:"إسناد الرياضيات إلى أ"}));fireEvent.click(screen.getByRole("checkbox",{name:/أحمد/}));fireEvent.click(screen.getByRole("button",{name:"معاينة الأثر"}));await waitFor(()=>expect(assignmentApi.preview).toHaveBeenCalledWith("s1",expect.objectContaining({subject_id:"sub1",teacher_ids:["t1"]})));expect(screen.getByRole("dialog")).toHaveTextContent("الأثر المتوقع من الخادم");expect(screen.getByRole("button",{name:"تأكيد الحفظ"})).toBeInTheDocument()});
 it("shows server-derived remaining coverage and workload before bulk apply",async()=>{render(<AssignmentWorkspace/>);await screen.findByText("إسناد المعلمين");const boxes=screen.getAllByRole("checkbox",{name:"اختيار الخلية للإسناد الجماعي"});fireEvent.click(boxes[0]);fireEvent.click(boxes[2]);expect(screen.getByText("2 خلية محددة لنفس المادة")).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"إسناد جماعي"}));fireEvent.change(screen.getByRole("combobox",{name:"المعلم"}),{target:{value:"t1"}});fireEvent.click(screen.getByRole("button",{name:"معاينة 2 خلية"}));await waitFor(()=>expect(assignmentApi.bulkPreview).toHaveBeenCalled());expect(screen.getByRole("dialog")).toHaveTextContent("المطلوب 6 · الحالي 4 · الإضافة 2 · المتوقع 6");expect(screen.getByRole("dialog")).toHaveTextContent("النصاب 5 + 2 = 7 / 4")});
 it("shows combined co-teaching groups and in-app delete confirmation",async()=>{render(<AssignmentWorkspace/>);await screen.findByText("إسناد المعلمين");fireEvent.click(screen.getByRole("button",{name:"قائمة الإسنادات"}));expect(screen.getByText("الأول المتوسط / أ، الأول المتوسط / ب")).toBeInTheDocument();expect(screen.getByText(/تدريس مشترك/)).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"حذف"}));expect(screen.getByRole("alertdialog")).toHaveTextContent("روابط المعلمين والشعب والموارد")});
 it("previews bulk removal from the advanced list",async()=>{render(<AssignmentWorkspace/>);await screen.findByText("إسناد المعلمين");fireEvent.click(screen.getByRole("button",{name:"قائمة الإسنادات"}));fireEvent.click(screen.getByRole("checkbox",{name:"اختيار الإسناد"}));fireEvent.click(screen.getByRole("button",{name:"حذف المحدد"}));expect(screen.getByRole("alertdialog")).toHaveTextContent("ستتأثر 1 مجموعة تدريس")});
});
