"use client";

import { FormEvent,useCallback,useEffect,useMemo,useState } from "react";
import { masterApi,type CatalogSnapshot } from "@/lib/master-api";
import type { Item } from "@/lib/setup-api";
type Tab="subjects"|"requirements"|"resources"; const val=(x:unknown)=>String(x??"");
const resourceNames:Record<string,string>={room:"فصل / غرفة",science_lab:"مختبر علوم",computer_lab:"معمل حاسب",gym:"صالة رياضية",library:"مصادر تعلم / مكتبة",field:"ملعب",other:"مورد آخر"};

export function CatalogWorkspace(){
 const[schoolId,setSchoolId]=useState("");const[data,setData]=useState<CatalogSnapshot|null>(null);const[tab,setTab]=useState<Tab>("subjects");const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[edit,setEdit]=useState<Item|null>(null);const[remove,setRemove]=useState<Item|null>(null);const[search,setSearch]=useState("");const[gradeId,setGradeId]=useState("");const[message,setMessage]=useState("");const[error,setError]=useState("");
 const load=useCallback(async(id?:string)=>{const school=id??localStorage.getItem("pm-school")??"";if(!school){setLoading(false);return}setSchoolId(school);setLoading(true);try{setData(await masterApi.catalog(school));setError("")}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);const handler=(e:Event)=>void load((e as CustomEvent<string>).detail);window.addEventListener("pm-school-change",handler);return()=>{clearTimeout(timer);window.removeEventListener("pm-school-change",handler)}},[load]);
 const activeGrade=data?.grades.some(g=>g.id===gradeId)?gradeId:data?.grades[0]?.id??"";const gradeRequirements=data?.requirements.filter(r=>r.grade_id===activeGrade)??[];const total=gradeRequirements.reduce((sum,r)=>sum+Number(r.weekly_occurrences),0);
 const visible=useMemo(()=>{const rows=tab==="subjects"?data?.subjects:tab==="resources"?data?.resources:data?.requirements;return rows?.filter(x=>[x.name_ar,x.code].some(v=>val(v).toLowerCase().includes(search.toLowerCase())))??[]},[data,tab,search]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),get=(k:string)=>val(f.get(k));let payload:object;if(tab==="subjects")payload={code:get("code"),name_ar:get("name_ar"),name_en:get("name_en")||null,is_active:f.get("active")==="on"};else if(tab==="resources")payload={code:get("code"),name_ar:get("name_ar"),resource_type:get("type"),capacity:get("capacity")?Number(get("capacity")):null,exclusive:f.get("exclusive")==="on",is_active:f.get("active")==="on"};else payload={grade_id:get("grade_id"),subject_id:get("subject_id"),weekly_occurrences:Number(get("weekly")),notes:get("notes")||null};setBusy(true);setError("");try{const kind=tab;if(edit)await masterApi.updateCatalog(schoolId,kind,edit.id,payload);else await masterApi.createCatalog(schoolId,kind,payload);setEdit(null);e.currentTarget.reset();setMessage("تم حفظ البيانات");await load(schoolId)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(loading)return <section className="content"><div className="skeleton" aria-label="جار تحميل المواد والموارد"/></section>;
 return <section className="content master-page"><div className="page-heading"><div><span className="eyebrow">{data?.school.name_ar}</span><h1>المواد والمناهج والموارد</h1><p>بيانات المدرسة الأساسية قبل مرحلة الإسناد.</p></div></div>{message&&<div className="success-banner">✓ {message}</div>}{error&&<div className="error-banner">{error}</div>}
 <div className="workspace-tabs" role="tablist">{([["subjects","المواد"],["requirements","الأنصبة الأسبوعية"],["resources","الغرف والموارد"]] as [Tab,string][]).map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>{setTab(id);setEdit(null);setSearch("")}}>{label}</button>)}</div>
 {tab==="requirements"&&<div className="curriculum-summary"><label>الصف<select aria-label="اختيار الصف" value={activeGrade} onChange={e=>setGradeId(e.target.value)}>{data?.grades.map(g=><option value={g.id} key={g.id}>{val(data.stages.find(s=>s.id===g.stage_id)?.name_ar)} — {val(g.name_ar)}</option>)}</select></label><div><span>إجمالي الحصص المطلوبة للصف</span><strong>{total}</strong></div></div>}
 <div className="catalog-layout"><article className="form-card"><h2>{edit?"تعديل":"إضافة"} {tab==="subjects"?"مادة":tab==="resources"?"مورد":"نصاب أسبوعي"}</h2><p>{tab==="requirements"?"عدد الحصص فقط؛ توزيعها التفصيلي يأتي لاحقًا.":"تُحفظ البيانات مباشرة للمدرسة المختارة."}</p><form key={edit?.id??`new-${tab}`} onSubmit={save}>
 {tab==="subjects"&&<><div className="two-fields"><label>رمز المادة<input name="code" defaultValue={val(edit?.code)} required/></label><label>الاسم العربي<input name="name_ar" defaultValue={val(edit?.name_ar)} required/></label></div><label>الاسم الإنجليزي<input name="name_en" defaultValue={val(edit?.name_en)}/></label><label className="check-field"><input type="checkbox" name="active" defaultChecked={edit?Boolean(edit.is_active):true}/> المادة نشطة</label></>}
 {tab==="resources"&&<><div className="two-fields"><label>الرمز<input name="code" defaultValue={val(edit?.code)} required/></label><label>الاسم<input name="name_ar" defaultValue={val(edit?.name_ar)} required/></label></div><label>النوع<select name="type" defaultValue={val(edit?.resource_type)||"room"}>{Object.entries(resourceNames).map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></label><label>السعة<input type="number" min="1" name="capacity" defaultValue={val(edit?.capacity)}/></label><div className="two-fields"><label className="check-field"><input type="checkbox" name="exclusive" defaultChecked={edit?Boolean(edit.exclusive):true}/> استخدام حصري</label><label className="check-field"><input type="checkbox" name="active" defaultChecked={edit?Boolean(edit.is_active):true}/> المورد نشط</label></div></>}
 {tab==="requirements"&&<><label>الصف<select name="grade_id" defaultValue={val(edit?.grade_id)||activeGrade}>{data?.grades.map(g=><option value={g.id} key={g.id}>{val(g.name_ar)}</option>)}</select></label><label>المادة<select name="subject_id" defaultValue={val(edit?.subject_id)}>{data?.subjects.map(s=><option value={s.id} key={s.id}>{val(s.name_ar)}</option>)}</select></label><label>الحصص الأسبوعية<input type="number" min="1" max="60" name="weekly" defaultValue={val(edit?.weekly_occurrences)||1} required/></label><label>ملاحظات<input name="notes" defaultValue={val(edit?.notes)}/></label></>}
 <div className="dialog-actions">{edit&&<button type="button" className="secondary" onClick={()=>setEdit(null)}>إلغاء التعديل</button>}<button className="primary" disabled={busy}>{busy?"جار الحفظ…":"حفظ"}</button></div></form></article>
 <article className="catalog-list"><div className="list-heading"><div><h2>{tab==="subjects"?"مواد المدرسة":tab==="resources"?"الغرف والموارد":"متطلبات الصف"}</h2><p>{tab==="requirements"?`${gradeRequirements.length} مواد · ${total} حصة أسبوعية`:`${visible.length} سجل`}</p></div>{tab!=="requirements"&&<input aria-label="بحث" value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث…"/>}</div>{(tab==="requirements"?gradeRequirements:visible).length===0?<div className="inline-empty">لا توجد بيانات بعد.</div>:<div className="data-table">{(tab==="requirements"?gradeRequirements:visible).map(item=><div className="data-row" key={item.id}><div><strong>{tab==="requirements"?val(data?.subjects.find(s=>s.id===item.subject_id)?.name_ar):val(item.name_ar)}</strong><span>{tab==="requirements"?`${item.weekly_occurrences} حصص أسبوعيًا`:tab==="resources"?`${val(item.code)} · ${resourceNames[val(item.resource_type)]}`:val(item.code)}</span></div>{tab==="requirements"&&<b>{val(item.weekly_occurrences)}</b>}<div className="row-actions"><button onClick={()=>setEdit(item)}>تعديل</button><button className="danger-link" onClick={()=>setRemove(item)}>حذف</button></div></div>)}</div>}</article></div>
 {remove&&<div className="dialog-backdrop"><section className="confirm-dialog" role="alertdialog" aria-modal="true"><h2>تأكيد الحذف</h2><p>لن تُحذف أي بيانات مرتبطة بصمت. سيخبرك النظام إذا كان السجل مستخدمًا.</p><div className="dialog-actions"><button className="secondary" onClick={()=>setRemove(null)}>إلغاء</button><button className="danger-button" onClick={async()=>{setBusy(true);try{await masterApi.deleteCatalog(schoolId,tab,remove.id);setRemove(null);setMessage("تم الحذف");await load(schoolId)}catch(e){setError((e as Error).message);setRemove(null)}finally{setBusy(false)}}}>حذف</button></div></section></div>}
 </section>;
}
