"use client";

import { FormEvent,useCallback,useEffect,useMemo,useState } from "react";
import { importApi,type DetectedSheet,type ImportJob } from "@/lib/import-api";
import { setupApi,type SetupSnapshot } from "@/lib/setup-api";

const entityLabels:Record<string,string>={teachers:"المعلمون",subjects:"المواد",structure:"الهيكل الدراسي",curriculum:"الأنصبة الأسبوعية",resources:"الغرف والموارد",offerings:"شُعب الفصل الدراسي",assignments:"الإسنادات",skip:"تخطي الورقة"};
const fieldLabels:Record<string,string>={teacher_name:"اسم المعلم",teacher_code:"كود المعلم",specialty:"التخصص",subject_name:"اسم المادة",subject_code:"رمز المادة",stage_name:"المرحلة",stage_code:"رمز المرحلة",grade_name:"الصف",section_name:"الشعبة",weekly_occurrences:"عدد الحصص",resource_name:"المورد",resource_code:"رمز المورد",resource_type:"نوع المورد",capacity:"السعة",shift_name:"الشفت",group_key:"مفتاح المجموعة"};
const actionLabels:Record<string,string>={create:"إنشاء",link_existing:"ربط موجود",update:"تحديث صريح",skip_unchanged:"دون تغيير",warning:"تحذير",conflict:"تعارض"};

export function ImportWorkspace(){
 const [schoolId,setSchoolId]=useState("");const [setup,setSetup]=useState<SetupSnapshot|null>(null);const [termId,setTermId]=useState("");const [job,setJob]=useState<ImportJob|null>(null);const [file,setFile]=useState<File|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");const [filter,setFilter]=useState("all");const [ack,setAck]=useState(false);
 const bootstrap=useCallback(async(id?:string)=>{const school=id??localStorage.getItem("pm-school")??"";if(!school)return;setSchoolId(school);try{const data=await setupApi.snapshot(school);setSetup(data);const current=data.years.find(y=>y.is_current);setTermId(String(data.terms.find(t=>t.academic_year_id===current?.id)?.id??data.terms[0]?.id??""))}catch(e){setError((e as Error).message)}},[]);
 useEffect(()=>{const timer=setTimeout(()=>void bootstrap(),0);const handler=(e:Event)=>void bootstrap((e as CustomEvent<string>).detail);window.addEventListener("pm-school-change",handler);return()=>{clearTimeout(timer);window.removeEventListener("pm-school-change",handler)}},[bootstrap]);
 async function upload(e:FormEvent){e.preventDefault();if(!file){setError("اختر ملفًا أولًا.");return}setBusy(true);setError("");try{const next=await importApi.upload(schoolId,file,termId||undefined);if(file.name.toLowerCase().endsWith(".xml")){const sheets=Object.fromEntries(next.detected_sheets.map(sheet=>[sheet.name,{entity_type:sheet.entity_type,columns:sheet.suggested_mapping}]));const mapped=await importApi.mapping(schoolId,next.id,{sheets,allow_updates:false});setJob(await importApi.validate(schoolId,mapped.id));setMessage("تم فحص ملف Timetables وتجهيز البيانات للمعاينة. لم تُحفظ البيانات بعد.")}else{setJob(next);setMessage("تم رفع الملف وفحص بنيته واكتشاف الأوراق")}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function saveMapping(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!job)return;const form=new FormData(e.currentTarget);const sheets:Record<string,object>={};for(const sheet of job.detected_sheets){const entity=String(form.get(`entity:${sheet.name}`));const columns:Record<string,string>={};for(const header of sheet.headers){const target=String(form.get(`map:${sheet.name}:${header}`)??"");if(target)columns[header]=target}sheets[sheet.name]={entity_type:entity,columns}}setBusy(true);try{const mapped=await importApi.mapping(schoolId,job.id,{sheets,allow_updates:form.get("updates")==="on"});setJob(await importApi.validate(schoolId,mapped.id));setMessage("اكتمل التحقق الخادمي دون كتابة البيانات الأساسية") }catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function commit(){if(!job)return;setBusy(true);try{setJob(await importApi.commit(schoolId,job.id,ack));setMessage("تم الاستيراد ذريًا وحفظ ملخص النتيجة") }catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const shown=useMemo(()=>job?.rows.filter(row=>filter==="all"||filter==="errors"&&row.diagnostics.some(d=>d.severity==="error")||filter==="warnings"&&row.diagnostics.some(d=>d.severity==="warning")||row.proposed_action===filter)??[],[job,filter]);
 const isTimetables=job?.source_filename.toLowerCase().endsWith(".xml")??false;
 return <section className="content import-page"><div className="page-heading"><div><span className="eyebrow">استيراد مرحلي وآمن</span><h1>استيراد Excel وCSV وTimetables</h1><p>ارفع الملف، راجع الاكتشاف والمطابقة والتشخيصات، ثم أكد الكتابة الذرية.</p></div></div>{message&&<div className="success-banner" role="status">✓ {message}</div>}{error&&<div className="error-banner" role="alert">{error}</div>}
 <ol className="import-stepper" aria-label="مراحل الاستيراد">{["الرفع","الاكتشاف والمطابقة","التحقق","المعاينة","التأكيد","النتائج"].map((label,index)=><li className={(job?job.status==="committed"?5:job.status==="ready"||job.status==="validated"?3:1:0)>=index?"active":""} key={label}>{index+1}<span>{label}</span></li>)}</ol>
 {!job&&<><form className="upload-card" onSubmit={upload}><label>الفصل الدراسي المستهدف<select aria-label="الفصل الدراسي المستهدف" value={termId} onChange={e=>setTermId(e.target.value)}><option value="">غير مطلوب لهذا النوع</option>{setup?.terms.map(t=><option value={String(t.id)} key={String(t.id)}>{String(t.name_ar)}</option>)}</select></label><label className="drop-zone">اسحب ملف CSV أو XLSX أو XML من Timetables هنا، أو اختره<input aria-label="اختيار ملف الاستيراد" type="file" accept=".csv,.xlsx,.xml" onChange={e=>setFile(e.target.files?.[0]??null)}/><strong>{file?.name??"لم يُختر ملف"}</strong><small>الحد الافتراضي 10 MB — يدعم XML الصادر من aSc Timetables ولا يقبل الصيغ التنفيذية</small></label><button className="primary" disabled={busy}>رفع وفحص الملف</button></form><TemplateLinks schoolId={schoolId}/></>}
 {job&&job.status!=="committed"&&<><div className="import-meta"><strong>{job.source_filename}</strong><span>{job.rows.length} سجلًا جاهزًا للفحص</span>{!isTimetables&&<code>{job.file_sha256.slice(0,12)}…</code>}{job.duplicate_file_warning&&<b>سبق استيراد ملف مطابق لهذا الهدف</b>}</div>{isTimetables&&<TimetablesSummary job={job}/>} {!isTimetables&&<form className="mapping-workspace" onSubmit={saveMapping}>{job.detected_sheets.map(sheet=><SheetMapper key={sheet.name} sheet={sheet}/>) }<label className="check-field"><input type="checkbox" name="updates"/>السماح بتحديثات صريحة مع عرض قبل/بعد</label><button className="primary" disabled={busy}>حفظ المطابقة والتحقق</button></form>}
 {job.validation_summary.total!==undefined&&<><div className="validation-summary" role="status"><Metric label="الإجمالي" value={job.validation_summary.total}/><Metric label="جاهز للاستيراد" value={job.validation_summary.valid}/><Metric label="تنبيهات" value={job.validation_summary.warnings}/><Metric label="يحتاج معالجة" value={job.validation_summary.errors}/></div>{!isTimetables&&<><div className="row-toolbar"><label>تصفية الصفوف<select aria-label="تصفية الصفوف" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">الكل</option><option value="errors">أخطاء</option><option value="warnings">تحذيرات</option>{Object.entries(actionLabels).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label></div><ImportRows rows={shown}/></>}{isTimetables&&Number(job.validation_summary.errors)>0&&<div className="xml-problems"><h2>بيانات تحتاج مراجعة قبل الاستيراد</h2>{job.rows.filter(row=>row.diagnostics.some(item=>item.severity==="error")).map(row=><div key={row.id}><strong>{entityLabels[row.entity_type]??row.entity_type}</strong>{row.diagnostics.filter(item=>item.severity==="error").map(item=><p key={`${item.code}-${item.field}`}>{item.message_ar}</p>)}</div>)}</div>}{Number(job.validation_summary.errors)===0&&<div className="commit-card"><h2>{isTimetables?"البيانات جاهزة":"تأكيد الاستيراد"}</h2><p>{isTimetables?"لم تُحفظ أي بيانات حتى الآن. عند الضغط على الزر ستُضاف البيانات كلها معًا، وإذا حدث خطأ فلن يُحفظ أي جزء.":"المعاينة لم تكتب أي بيانات أساسية. عند التأكيد تُنفذ الإجراءات كلها داخل عملية واحدة، ويُلغى الكل عند أي فشل."}</p>{Number(job.validation_summary.warnings)>0&&<label className="check-field"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>اطلعت على التنبيهات وأوافق على المتابعة</label>}<button className="primary" disabled={busy||Number(job.validation_summary.warnings)>0&&!ack} onClick={()=>void commit()}>{isTimetables?"اعتماد واستيراد البيانات":"تأكيد الاستيراد الذري"}</button></div>}</>}</>}
 {job?.status==="committed"&&<div className="result-card"><span>اكتمل الاستيراد</span><h2>حُفظت البيانات بنجاح</h2><p>{isTimetables?"أصبحت بيانات Timetables متاحة الآن في المعلمين والصفوف والمواد والإسناد.":"اكتملت عملية الاستيراد وحُفظت نتيجتها."}</p>{!isTimetables&&<pre>{JSON.stringify(job.result_summary,null,2)}</pre>}<button className="primary" onClick={()=>{setJob(null);setFile(null)}}>استيراد ملف آخر</button></div>}
 </section>
}

function SheetMapper({sheet}:{sheet:DetectedSheet}){return <fieldset className="sheet-card"><legend>{sheet.name} · {sheet.row_count} صف</legend><label>نوع البيانات<select name={`entity:${sheet.name}`} defaultValue={sheet.entity_type}>{Object.entries(entityLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><p>ثقة الاكتشاف {Math.round(sheet.confidence*100)}% — راجع كل عمود ويمكنك تغيير الاقتراح.</p><div className="column-map">{sheet.headers.map(header=><label key={header}><span>{header||"عمود بلا عنوان"}</span><select aria-label={`مطابقة ${header}`} name={`map:${sheet.name}:${header}`} defaultValue={sheet.suggested_mapping[header]??""}><option value="">تجاهل العمود</option>{Object.entries(fieldLabels).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label>)}</div></fieldset>}
function Metric({label,value}:{label:string;value:unknown}){return <div><span>{label}</span><strong>{String(value??0)}</strong></div>}
function TimetablesSummary({job}:{job:ImportJob}){return <section className="xml-summary" aria-label="ملخص ملف Timetables"><div><span>تم التعرف على الملف تلقائيًا</span><h2>ماذا وجدنا في ملف Timetables؟</h2><p>راجع الأعداد فقط. لا تحتاج إلى مطابقة أعمدة أو التعامل مع أكواد داخلية.</p></div><div className="xml-summary-grid">{job.detected_sheets.map(sheet=><article key={sheet.name}><strong>{sheet.row_count}</strong><span>{entityLabels[sheet.entity_type]??sheet.name}</span></article>)}</div><p className="xml-note">لن نستبدل الجدول القديم الموجود في الملف. سنستورد بيانات المدرسة والإسنادات لتتمكن من إنشاء جدول جديد داخل التطبيق.</p></section>}
function ImportRows({rows}:{rows:ImportJob["rows"]}){return <div className="import-table-wrap"><table className="import-table"><thead><tr><th>الورقة / الصف</th><th>النوع</th><th>الإجراء المقترح</th><th>التشخيص</th><th>قبل / بعد</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.sheet_name} · {row.source_row_number}</td><td>{entityLabels[row.entity_type]??row.entity_type}</td><td><b>{actionLabels[row.proposed_action]??row.proposed_action}</b></td><td>{row.diagnostics.length?row.diagnostics.map(d=><p className={`diag-${d.severity}`} key={`${d.code}-${d.field}`}>{d.message_ar} <small>{d.field&&`(${fieldLabels[d.field]??d.field})`}</small></p>):"سليم"}</td><td><small>{Object.keys(row.before_values).length?JSON.stringify(row.before_values):"—"} ← {JSON.stringify(row.after_values)}</small></td></tr>)}</tbody></table></div>}
function TemplateLinks({schoolId}:{schoolId:string}){return <section className="template-card"><h2>قوالب عربية جاهزة</h2><div>{["teachers","subjects","structure","curriculum","resources","assignments"].map(kind=><button type="button" key={kind} onClick={()=>void importApi.downloadTemplate(schoolId,kind)}>{entityLabels[kind]}</button>)}</div></section>}
