import {cleanup,fireEvent,render,screen,waitFor} from "@testing-library/react";
import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import {importApi,type ImportJob} from "@/lib/import-api";
import {setupApi} from "@/lib/setup-api";
import {ImportWorkspace} from "./import-workspace";

const setup={school:{id:"s1",name_ar:"مدرسة النور",code:"S1"},years:[{id:"y1",name:"1448",is_current:true}],terms:[{id:"term1",academic_year_id:"y1",name_ar:"الفصل الأول"}],shifts:[],patterns:[],days:[],blocks:[],stages:[],grades:[],sections:[]};
const uploaded:ImportJob={id:"j1",school_id:"s1",term_id:"term1",source_filename:"teachers.csv",file_size:50,file_sha256:"abcdef1234567890",status:"uploaded",duplicate_file_warning:false,mapping:{},validation_summary:{},result_summary:{},detected_sheets:[{name:"CSV",headers:["اسم المعلم","كود المعلم"],entity_type:"teachers",confidence:1,suggested_mapping:{"اسم المعلم":"teacher_name","كود المعلم":"teacher_code"},row_count:1}],rows:[{id:"row1",sheet_name:"CSV",source_row_number:2,entity_type:"teachers",source_values:{"اسم المعلم":"أحمد","كود المعلم":"T1"},normalized_values:{},proposed_action:"warning",diagnostics:[],before_values:{},after_values:{},excluded:false,group_key:null}]};
const ready:ImportJob={...uploaded,status:"ready",validation_summary:{total:1,valid:1,warnings:1,errors:0,actions:{link_existing:1}},rows:[{...uploaded.rows[0],proposed_action:"link_existing",normalized_values:{teacher_name:"أحمد",teacher_code:"T1"},after_values:{teacher_name:"أحمد"},diagnostics:[{sheet:"CSV",row:2,field:"teacher_code",severity:"warning",code:"existing",message_ar:"سيُربط المعلم الموجود",resolution_ar:"راجع الكود"}]}]};
const xmlUploaded:ImportJob={...uploaded,id:"xml1",source_filename:"school.xml",status:"uploaded",detected_sheets:[{name:"المعلمون من Timetables",headers:["اسم المعلم"],entity_type:"teachers",confidence:1,suggested_mapping:{"اسم المعلم":"teacher_name"},row_count:22},{name:"المواد من Timetables",headers:["اسم المادة"],entity_type:"subjects",confidence:1,suggested_mapping:{"اسم المادة":"subject_name"},row_count:11}],rows:[]};
const xmlReady:ImportJob={...xmlUploaded,status:"ready",validation_summary:{total:33,valid:33,warnings:0,errors:0},rows:[]};
vi.mock("@/lib/setup-api",()=>({setupApi:{snapshot:vi.fn()}}));
vi.mock("@/lib/import-api",()=>({importApi:{upload:vi.fn(),get:vi.fn(),mapping:vi.fn(),validate:vi.fn(),exclude:vi.fn(),commit:vi.fn(),downloadTemplate:vi.fn()}}));

describe("smart import workspace",()=>{beforeEach(()=>{Object.defineProperty(window,"localStorage",{configurable:true,value:{getItem:()=>"s1"}});vi.mocked(setupApi.snapshot).mockResolvedValue(setup);vi.mocked(importApi.upload).mockResolvedValue(uploaded);vi.mocked(importApi.mapping).mockResolvedValue({...uploaded,status:"mapped"});vi.mocked(importApi.validate).mockResolvedValue(ready)});afterEach(()=>{cleanup();vi.clearAllMocks()});
 it("shows an Arabic upload step with school term scope and authenticated templates",async()=>{render(<ImportWorkspace/>);expect(await screen.findByText("استيراد Excel وCSV وTimetables")).toBeInTheDocument();await waitFor(()=>expect(screen.getByRole("combobox",{name:"الفصل الدراسي المستهدف"})).toHaveValue("term1"));expect(screen.getByLabelText("اختيار ملف الاستيراد")).toHaveAttribute("accept",".csv,.xlsx,.xml");fireEvent.click(screen.getByRole("button",{name:"المعلمون"}));expect(importApi.downloadTemplate).toHaveBeenCalledWith("s1","teachers")});
 it("uploads then allows detection and mapping override before validation",async()=>{render(<ImportWorkspace/>);await screen.findByText("استيراد Excel وCSV وTimetables");const file=new File(["اسم المعلم,كود المعلم\nأحمد,T1"],"teachers.csv",{type:"text/csv"});fireEvent.change(screen.getByLabelText("اختيار ملف الاستيراد"),{target:{files:[file]}});fireEvent.click(screen.getByRole("button",{name:"رفع وفحص الملف"}));await screen.findByText("CSV · 1 صف");const mapping=screen.getByRole("combobox",{name:"مطابقة اسم المعلم"});fireEvent.change(mapping,{target:{value:"specialty"}});fireEvent.click(screen.getByRole("button",{name:"حفظ المطابقة والتحقق"}));await waitFor(()=>expect(importApi.mapping).toHaveBeenCalledWith("s1","j1",expect.objectContaining({sheets:expect.objectContaining({CSV:expect.objectContaining({columns:expect.objectContaining({"اسم المعلم":"specialty"})})})})));expect(importApi.validate).toHaveBeenCalledWith("s1","j1")});
 it("auto-maps Timetables XML and shows a simple confirmation summary",async()=>{vi.mocked(importApi.upload).mockResolvedValue(xmlUploaded);vi.mocked(importApi.mapping).mockResolvedValue({...xmlUploaded,status:"mapped"});vi.mocked(importApi.validate).mockResolvedValue(xmlReady);render(<ImportWorkspace/>);await screen.findByText("استيراد Excel وCSV وTimetables");const file=new File(["<xml/>"],"school.xml",{type:"application/xml"});fireEvent.change(screen.getByLabelText("اختيار ملف الاستيراد"),{target:{files:[file]}});fireEvent.click(screen.getByRole("button",{name:"رفع وفحص الملف"}));expect(await screen.findByText("ماذا وجدنا في ملف Timetables؟")).toBeInTheDocument();expect(screen.queryByText("نوع البيانات")).not.toBeInTheDocument();expect(screen.getByRole("button",{name:"اعتماد واستيراد البيانات"})).toBeEnabled();expect(importApi.mapping).toHaveBeenCalledWith("s1","xml1",expect.objectContaining({allow_updates:false}));expect(importApi.validate).toHaveBeenCalledWith("s1","xml1")});
 it("shows row numbers diagnostics action counts and warning filtering",async()=>{vi.mocked(importApi.upload).mockResolvedValue(ready);render(<ImportWorkspace/>);await screen.findByText("استيراد Excel وCSV وTimetables");const file=new File(["x"],"teachers.csv");fireEvent.change(screen.getByLabelText("اختيار ملف الاستيراد"),{target:{files:[file]}});fireEvent.click(screen.getByRole("button",{name:"رفع وفحص الملف"}));expect(await screen.findByText("سيُربط المعلم الموجود")).toBeInTheDocument();expect(screen.getByText("CSV · 2")).toBeInTheDocument();expect(screen.getAllByText("ربط موجود").length).toBeGreaterThan(0);fireEvent.change(screen.getByRole("combobox",{name:"تصفية الصفوف"}),{target:{value:"warnings"}});expect(screen.getByText("سيُربط المعلم الموجود")).toBeInTheDocument()});
 it("requires in-app warning acknowledgement and shows durable final results",async()=>{vi.mocked(importApi.upload).mockResolvedValue(ready);vi.mocked(importApi.commit).mockResolvedValue({...ready,status:"committed",result_summary:{linked:1}});render(<ImportWorkspace/>);await screen.findByText("استيراد Excel وCSV وTimetables");const file=new File(["x"],"teachers.csv");fireEvent.change(screen.getByLabelText("اختيار ملف الاستيراد"),{target:{files:[file]}});fireEvent.click(screen.getByRole("button",{name:"رفع وفحص الملف"}));const commit=await screen.findByRole("button",{name:"تأكيد الاستيراد الذري"});expect(commit).toBeDisabled();fireEvent.click(screen.getByRole("checkbox",{name:/اطلعت على التنبيهات/}));fireEvent.click(commit);expect(await screen.findByText("حُفظت البيانات بنجاح")).toBeInTheDocument();expect(importApi.commit).toHaveBeenCalledWith("s1","j1",true)});
});
