"use client";

import { ChangeEvent, useEffect, useMemo, useState } from "react";
import { projectApi, type Project } from "@/lib/project-api";
import { reportApi, type ReportDataset, type ReportOptions, type ReportRequest, type ReportType } from "@/lib/report-api";

const TYPES:Array<[ReportType,string]>=[["general_timetable","الجدول العام"],["section_timetable","جدول الشعبة"],["teacher_timetable","جدول المعلم"],["subject_timetable","جدول المادة"],["resource_timetable","جدول المورد / المعمل"],["daily_substitutions","البدلاء اليومي"],["waiting_workload","الانتظار والحمولة"]];
const EMPTY:ReportOptions={schools:[],teachers:[],sections:[],subjects:[],resources:[]};
const weekdays=["كل الأيام","الأحد","الاثنين","الثلاثاء","الأربعاء","الخميس","الجمعة","السبت"];

export function ReportWorkspace(){
  const [projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(""),[options,setOptions]=useState<ReportOptions>(EMPTY);
  const [type,setType]=useState<ReportType>("general_timetable"),[filterId,setFilterId]=useState(""),[schoolId,setSchoolId]=useState(""),[date,setDate]=useState(new Date().toISOString().slice(0,10));
  const [week,setWeek]=useState(""),[weekday,setWeekday]=useState(""),[paper,setPaper]=useState<"A4"|"A3">("A4"),[orientation,setOrientation]=useState<"portrait"|"landscape">("landscape"),[theme,setTheme]=useState<"color"|"monochrome">("color");
  const [showTime,setShowTime]=useState(true),[showResource,setShowResource]=useState(true),[footer,setFooter]=useState(""),[qr,setQr]=useState(""),[signatures,setSignatures]=useState("مدير المدرسة"); const [logo,setLogo]=useState("");
  const [dataset,setDataset]=useState<ReportDataset|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
  useEffect(()=>{projectApi.list().then(rows=>{setProjects(rows);setProjectId(rows[0]?.id??"")}).catch(()=>setError("تعذر تحميل مشاريع الجداول."));},[]);
  useEffect(()=>{if(projectId)reportApi.options(projectId).then(setOptions).catch(e=>setError(e.message));},[projectId]);
  const filter=useMemo(()=>type==="section_timetable"?["section_id",options.sections,"الشعبة"] as const:type==="teacher_timetable"?["teacher_id",options.teachers,"المعلم"] as const:type==="subject_timetable"?["subject_id",options.subjects,"المادة"] as const:type==="resource_timetable"?["resource_id",options.resources,"المورد"] as const:null,[type,options]);
  function payload(revision?:number):ReportRequest{const filters:Record<string,string|number|undefined>={school_id:schoolId||undefined,project_cycle_week_index:week===""?undefined:Number(week),weekday_index:weekday===""?undefined:Number(weekday)};if(filter&&filterId)filters[filter[0]]=filterId;if(type==="daily_substitutions"||type==="waiting_workload")filters.on_date=date;return{report_type:type,source:{kind:"working",expected_revision:revision},filters,print_options:{paper,orientation,density:"compact",theme,show_heading:true,show_period_time:showTime,show_resource:showResource},branding:{logo_data_url:logo||undefined,qr_payload:qr||undefined,footer_text:footer||undefined,signature_labels:signatures.split("،").map(x=>x.trim()).filter(Boolean)}};}
  async function preview(){if(!projectId)return;setBusy(true);setError("");setMessage("");try{setDataset(await reportApi.preview(projectId,payload()));}catch(e){setError(e instanceof Error?e.message:"تعذر إعداد التقرير.");}finally{setBusy(false)}}
  async function download(format:"pdf"|"xlsx"|"png"){if(!dataset||dataset.source.revision===null)return;setBusy(true);setError("");try{const result=await reportApi.export(projectId,payload(dataset.source.revision),format);const url=URL.createObjectURL(result.blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=result.filename;anchor.click();URL.revokeObjectURL(url);setMessage(result.multiPage?`تم تجهيز ${result.pages} صفحات داخل ملف ZIP.`:"تم تجهيز ملف التصدير بنجاح.");}catch(e){setError(e instanceof Error?e.message:"تعذر التصدير.");}finally{setBusy(false)}}
  function pickLogo(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;if(!["image/png","image/jpeg"].includes(file.type)||file.size>1_000_000){setError("اختر شعار PNG أو JPEG بحجم لا يتجاوز 1MB.");return;}const reader=new FileReader();reader.onload=()=>setLogo(String(reader.result));reader.readAsDataURL(file);}
  return <section className="workspace report-space" aria-labelledby="reports-title"><div className="page-title"><div><span className="eyebrow">مخرجات المدرسة</span><h1 id="reports-title">التقارير والطباعة</h1><p>أنشئ معاينة server-side من نسخة الجدول الحالية ثم صدّرها بصيغة حقيقية.</p></div>{dataset&&<span className="revision-chip">نسخة الجدول {dataset.source.revision}</span>}</div>
    {error&&<div role="alert" className="error-banner">{error}</div>}{message&&<div role="status" className="success-banner">{message}</div>}
    <div className="report-steps"><article><h2><b>1</b> نوع التقرير</h2><label>مشروع الجداول<select aria-label="مشروع الجداول" value={projectId} onChange={e=>setProjectId(e.target.value)}>{projects.map(p=><option key={p.id} value={p.id}>{p.name_ar}</option>)}</select></label><div className="report-types">{TYPES.map(([value,label])=><button type="button" aria-pressed={type===value} className={type===value?"selected":""} key={value} onClick={()=>{setType(value);setFilterId("");setDataset(null)}}>{label}</button>)}</div></article>
    <article><h2><b>2</b> الفلاتر</h2><div className="form-grid"><label>المدرسة<select aria-label="فلتر المدرسة" value={schoolId} onChange={e=>setSchoolId(e.target.value)}><option value="">كل مدارس المشروع</option>{options.schools.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>{filter&&<label>{filter[2]}<select aria-label={`اختيار ${filter[2]}`} required value={filterId} onChange={e=>setFilterId(e.target.value)}><option value="">اختر</option>{filter[1].filter(x=>!schoolId||x.school_ids.includes(schoolId)).map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>}{(type==="daily_substitutions"||type==="waiting_workload")&&<label>التاريخ<input aria-label="تاريخ التقرير" type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>}{!type.includes("substitution")&&type!=="waiting_workload"&&<><label>أسبوع دورة المشروع<input aria-label="أسبوع دورة المشروع" type="number" min="0" placeholder="الكل" value={week} onChange={e=>setWeek(e.target.value)}/></label><label>اليوم<select aria-label="اليوم" value={weekday} onChange={e=>setWeekday(e.target.value)}>{weekdays.map((x,i)=><option key={x} value={i?i-1:""}>{x}</option>)}</select></label></>}</div><button className="primary" disabled={busy||!projectId||Boolean(filter&&!filterId)} onClick={preview}>{busy?"جارٍ إعداد المعاينة…":"معاينة التقرير"}</button></article>
    <article><h2><b>3</b> إعدادات الطباعة</h2><div className="form-grid"><label>المقاس<select aria-label="مقاس الورق" value={paper} onChange={e=>setPaper(e.target.value as "A4"|"A3")}><option>A4</option><option>A3</option></select></label><label>الاتجاه<select aria-label="اتجاه الصفحة" value={orientation} onChange={e=>setOrientation(e.target.value as "portrait"|"landscape")}><option value="landscape">أفقي</option><option value="portrait">عمودي</option></select></label><label>الألوان<select aria-label="نمط الألوان" value={theme} onChange={e=>setTheme(e.target.value as "color"|"monochrome")}><option value="color">ملون</option><option value="monochrome">أحادي اللون</option></select></label><label>QR<input aria-label="محتوى QR" value={qr} onChange={e=>setQr(e.target.value)} placeholder="رابط أو مرجع موثوق"/></label><label>التذييل<input aria-label="نص التذييل" value={footer} onChange={e=>setFooter(e.target.value)}/></label><label>التواقيع<input aria-label="مسميات التوقيع" value={signatures} onChange={e=>setSignatures(e.target.value)}/></label><label>الشعار<input aria-label="رفع الشعار" type="file" accept="image/png,image/jpeg" onChange={pickLogo}/></label></div><div className="checks"><label><input type="checkbox" checked={showTime} onChange={e=>setShowTime(e.target.checked)}/> إظهار الوقت</label><label><input type="checkbox" checked={showResource} onChange={e=>setShowResource(e.target.checked)}/> إظهار المورد</label></div></article></div>
    <article className="report-preview" aria-live="polite"><div className="preview-head"><div><h2>المعاينة</h2>{dataset&&<p>{dataset.row_count} سجل · المصدر: WorkingTimetable الحالية</p>}</div>{dataset&&<div className="export-actions"><button disabled={busy||dataset.stale} onClick={()=>download("pdf")}>تصدير PDF</button><button disabled={busy||dataset.stale} onClick={()=>download("xlsx")}>تصدير XLSX</button><button disabled={busy||dataset.stale} onClick={()=>download("png")}>تصدير PNG</button></div>}</div>{!dataset?<div className="empty-state">اختر التقرير والفلاتر ثم اضغط «معاينة التقرير».</div>:<>{dataset.warnings.map(x=><div className="warning-banner" key={x}>{x}</div>)}<div className="report-table-wrap"><table><caption>{dataset.title}</caption><thead><tr>{dataset.columns.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{dataset.rows.length?dataset.rows.map(row=><tr key={row.row_id}>{renderRow(dataset,row)}</tr>):<tr><td colSpan={dataset.columns.length}>لا توجد بيانات مطابقة.</td></tr>}</tbody></table></div></>}</article>
  </section>;
}

function renderRow(dataset:ReportDataset,row:ReportDataset["rows"][number]){const time=`${minutes(row.starts_at_minute)} - ${minutes(row.ends_at_minute)}`;let values:unknown[];if(dataset.report_type==="daily_substitutions")values=[row.weekday_label,time,row.school_name,row.absent_teacher_name,row.subject_name,(row.section_names??[]).join("، "),row.substitute_teacher_name??"غير مغطاة",row.coverage_status];else if(dataset.report_type==="waiting_workload")values=[(row.teacher_names??[]).join("، "),row.base_workload,row.teaching_workload,row.substitution_count,row.effective_limit,row.remaining_capacity,row.exempt?"مستثنى":"مشمول"];else values=[row.project_cycle_week_index,row.weekday_label,time,row.school_name,row.subject_name,(row.teacher_names??[]).join("، "),(row.section_names??[]).join("، "),(row.resource_names??[]).join("، "),row.attendance_label];if(!dataset.columns.includes("الوقت"))values.splice(dataset.report_type==="daily_substitutions"?1:2,1);if(dataset.report_type!=="daily_substitutions"&&dataset.report_type!=="waiting_workload"&&!dataset.columns.includes("المورد"))values.splice(values.length-2,1);return values.map((x,i)=><td key={i}>{String(x??"")}</td>)}
function minutes(value:unknown){return typeof value==="number"?`${String(Math.floor(value/60)).padStart(2,"0")}:${String(value%60).padStart(2,"0")}`:""}
