"use client";

import { useCallback, useEffect, useState } from "react";
import { setupApi, type Item, type SetupSnapshot } from "@/lib/setup-api";

const weekdays = ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"];
type Tab = "calendar" | "day" | "structure";

function field(form: FormData, name: string) { return String(form.get(name) ?? ""); }
function NameList({ title, items, resource, schoolId, reload, onEdit }: { title: string; items: Item[]; resource: string; schoolId: string; reload: () => void; onEdit?: (item: Item) => void }) {
  async function remove(item: Item) { if (!confirm(`هل تريد حذف «${item.name_ar ?? item.name ?? item.label_ar}»؟`)) return; try { await setupApi.remove(schoolId, resource, item.id); reload(); } catch (e) { alert((e as Error).message); } }
  return <div className="entity-list"><h3>{title}</h3>{items.length === 0 ? <p className="inline-empty">لم تتم إضافة بيانات بعد.</p> : items.map((x) => <div className="entity-row" key={x.id}><div><strong>{String(x.name_ar ?? x.name ?? x.label_ar)}</strong>{x.starts_on && <small>{String(x.starts_on)} — {String(x.ends_on)}</small>}</div><div>{onEdit && <button className="text-button" onClick={() => onEdit(x)} type="button">تعديل</button>}<button className="danger-link" onClick={() => remove(x)} type="button">حذف</button></div></div>)}</div>;
}

export function SetupWorkspace({ initialTab = "calendar" }: { initialTab?: Tab }) {
  const [schoolId, setSchoolId] = useState(""); const [data, setData] = useState<SetupSnapshot | null>(null);
  const [tab, setTab] = useState<Tab>(initialTab); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async (id?: string) => { const selected = id ?? localStorage.getItem("pm-school") ?? ""; if (!selected) { setLoading(false); return; } setSchoolId(selected); setLoading(true); try { setData(await setupApi.snapshot(selected)); setError(""); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); const handler = (e: Event) => void load((e as CustomEvent<string>).detail); window.addEventListener("pm-school-change", handler); return () => { window.clearTimeout(timer); window.removeEventListener("pm-school-change", handler); }; }, [load]);
  async function submit(resource: string, payload: object, form: HTMLFormElement) { setBusy(true); setError(""); try { await setupApi.create(schoolId, resource, payload); form.reset(); setNotice("تم الحفظ بنجاح"); await load(schoolId); setTimeout(() => setNotice(""), 2500); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  if (loading) return <section className="content"><div className="skeleton" aria-label="جار تحميل إعداد المدرسة" /></section>;
  if (!schoolId) return <section className="content"><div className="empty-state"><h2>لا توجد مدرسة متاحة</h2><p>أضف مدرسة أولًا إلى الحساب.</p></div></section>;
  if (!data) return <section className="content"><div className="error-banner">{error}<button onClick={() => load()}>إعادة المحاولة</button></div></section>;
  const years = data.years ?? [], terms = data.terms ?? [], shifts = data.shifts ?? [], patterns = data.patterns ?? [], days = data.days ?? [], blocks = data.blocks ?? [], stages = data.stages ?? [], grades = data.grades ?? [], sections = data.sections ?? [];
  return <section className="content setup-page">
    <div className="page-heading"><div><span className="eyebrow">{data.school.name_ar}</span><h1>{tab === "structure" ? "الهيكل الدراسي" : "إعداد المدرسة"}</h1><p>اضبط التقويم واليوم الدراسي والهيكل الأكاديمي من مكان واحد.</p></div><div className="completion"><strong>{years.length && shifts.length && patterns.length ? "جاهز للمتابعة" : "ابدأ بالبيانات الأساسية"}</strong><span>{years.length + terms.length + shifts.length + patterns.length + days.length + blocks.length} عنصر تقويم</span></div></div>
    <div className="workspace-tabs" role="tablist"><button onClick={() => setTab("calendar")} className={tab === "calendar" ? "active" : ""}>العام والفترات</button><button onClick={() => setTab("day")} className={tab === "day" ? "active" : ""}>اليوم الدراسي</button><button onClick={() => setTab("structure")} className={tab === "structure" ? "active" : ""}>المراحل والصفوف</button></div>
    {notice && <div className="success-banner" role="status">✓ {notice}</div>}{error && <div className="error-banner" role="alert">{error}</div>}
    {tab === "calendar" && <div className="setup-grid">
      <article className="form-card"><h2>عام دراسي جديد</h2><p>حدد المدة الكاملة للعام في هذه المدرسة.</p><form onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); submit("years", { name: field(f,"name"), starts_on: field(f,"starts"), ends_on: field(f,"ends"), is_current: true }, e.currentTarget); }}><label>اسم العام<input name="name" required placeholder="مثال: 1448 هـ" /></label><div className="two-fields"><label>يبدأ في<input type="date" name="starts" required /></label><label>ينتهي في<input type="date" name="ends" required /></label></div><button className="primary" disabled={busy}>حفظ العام</button></form><NameList title="الأعوام" items={years} resource="years" schoolId={schoolId} reload={() => load(schoolId)} /></article>
      <article className="form-card"><h2>الفصول الدراسية</h2><p>كل فصل مرتبط بعام المدرسة الحالي.</p><form onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); submit("terms", { academic_year_id: field(f,"year"), name_ar: field(f,"name"), order: Number(field(f,"order")), starts_on: field(f,"starts"), ends_on: field(f,"ends") }, e.currentTarget); }}><label>العام<select name="year" required>{years.map(x => <option key={x.id} value={x.id}>{String(x.name)}</option>)}</select></label><div className="two-fields"><label>اسم الفصل<input name="name" required /></label><label>الترتيب<input name="order" min="1" type="number" required /></label></div><div className="two-fields"><label>البداية<input type="date" name="starts" required /></label><label>النهاية<input type="date" name="ends" required /></label></div><button className="primary" disabled={busy || !years.length}>إضافة فصل</button></form><NameList title="الفصول" items={terms} resource="terms" schoolId={schoolId} reload={() => load(schoolId)} /></article>
      <article className="form-card"><h2>الفترات / الشفتات</h2><p>مثل الدوام الصباحي أو المسائي.</p><form onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); submit("shifts", { code: field(f,"code"), name_ar: field(f,"name"), order: shifts.length, is_active: true }, e.currentTarget); }}><div className="two-fields"><label>المسمى<input name="name" required placeholder="صباحي" /></label><label>الرمز<input name="code" required placeholder="AM" /></label></div><button className="primary" disabled={busy}>إضافة فترة</button></form><NameList title="الفترات" items={shifts} resource="shifts" schoolId={schoolId} reload={() => load(schoolId)} /></article>
      <article className="form-card"><h2>أنماط الأسابيع</h2><p>استخدم أسبوعًا واحدًا أو أضف A ثم B ثم C.</p><div className="pattern-picker">{["A","B","C"].map((code, i) => <button key={code} disabled={busy || patterns.some(p => p.cycle_week_index === i) || i > patterns.length} onClick={(e) => submit("patterns", { code, name_ar: `الأسبوع ${code}`, cycle_week_index: i }, e.currentTarget.closest("article")!.querySelector("form") ?? document.createElement("form"))}>+ الأسبوع {code}</button>)}</div><form hidden /><NameList title="الأنماط المفعلة" items={patterns} resource="patterns" schoolId={schoolId} reload={() => load(schoolId)} onEdit={async (item) => { const name = prompt("اسم نمط الأسبوع", String(item.name_ar)); if (!name) return; try { await setupApi.update(schoolId, "patterns", item.id, { code: item.code, name_ar: name, cycle_week_index: item.cycle_week_index }); setNotice("تم تحديث نمط الأسبوع"); await load(schoolId); } catch (e) { setError((e as Error).message); } }} /></article>
    </div>}
    {tab === "day" && <div className="day-layout"><article className="form-card"><h2>أيام الدراسة</h2><p>فعّل اليوم لكل شفت ونمط أسبوع.</p><form onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); const idx = Number(field(f,"weekday")); submit("days", { shift_id: field(f,"shift"), week_pattern_id: field(f,"pattern"), weekday_index: idx, enabled: true, label_ar: weekdays[idx] }, e.currentTarget); }}><label>الفترة<select name="shift" required>{shifts.map(x => <option value={x.id} key={x.id}>{String(x.name_ar)}</option>)}</select></label><label>نمط الأسبوع<select name="pattern" required>{patterns.map(x => <option value={x.id} key={x.id}>{String(x.name_ar)}</option>)}</select></label><label>اليوم<select name="weekday">{weekdays.map((x,i) => <option value={i} key={x}>{x}</option>)}</select></label><button className="primary" disabled={busy || !shifts.length || !patterns.length}>تفعيل اليوم</button></form><NameList title="الأيام المفعلة" items={days} resource="days" schoolId={schoolId} reload={() => load(schoolId)} /></article>
      <article className="form-card timeline-card"><h2>بناء اليوم بصريًا</h2><p>تمنع الخدمة أي تداخل زمني غير صحيح.</p><form onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); const type = field(f,"type"); submit("blocks", { school_day_id: field(f,"day"), block_order: blocks.length, label_ar: field(f,"label"), block_type: type, period_number: type === "lesson" ? Number(field(f,"number")) : null, starts_at: field(f,"starts"), ends_at: field(f,"ends"), attendance_mode: field(f,"mode") }, e.currentTarget); }}><label>اليوم<select name="day" required>{days.map(x => <option value={x.id} key={x.id}>{weekdays[Number(x.weekday_index)]} — {String(patterns.find(p => p.id === x.week_pattern_id)?.name_ar ?? "")}</option>)}</select></label><div className="two-fields"><label>النوع<select name="type"><option value="lesson">حصة</option><option value="assembly">طابور</option><option value="break">فسحة</option><option value="prayer">صلاة</option><option value="activity">نشاط</option><option value="custom">فترة مخصصة</option></select></label><label>المسمى<input name="label" required /></label></div><div className="three-fields"><label>من<input type="time" name="starts" required /></label><label>إلى<input type="time" name="ends" required /></label><label>رقم الحصة<input type="number" name="number" min="1" /></label></div><label>نمط الحضور<select name="mode"><option value="onsite">حضوري</option><option value="remote">عن بعد</option><option value="hybrid">هجين</option></select></label><button className="primary" disabled={busy || !days.length}>إضافة إلى اليوم</button></form><div className="timeline">{blocks.length === 0 ? <p className="inline-empty">ابدأ بإضافة الطابور أو أول حصة.</p> : blocks.sort((a,b) => String(a.starts_at).localeCompare(String(b.starts_at))).map(x => <div className={`time-block ${x.block_type}`} key={x.id}><time>{String(x.starts_at).slice(0,5)}<span>{String(x.ends_at).slice(0,5)}</span></time><div><strong>{String(x.label_ar)}</strong><small>{x.block_type === "lesson" ? `الحصة ${x.period_number}` : "غير تدريسية"} · {x.attendance_mode === "remote" ? "عن بعد" : x.attendance_mode === "hybrid" ? "هجين" : "حضوري"}</small></div><button onClick={() => confirm("حذف هذا العنصر من اليوم؟") && setupApi.remove(schoolId,"blocks",x.id).then(() => load(schoolId))}>×</button></div>)}</div></article></div>}
    {tab === "structure" && <div className="setup-grid structure-grid">
      <article className="form-card"><h2>المراحل</h2><p>المسميات مرنة ولا تفرض المنصة أسماء ثابتة.</p><form onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); submit("stages", { code: field(f,"code"), name_ar: field(f,"name"), order: stages.length }, e.currentTarget); }}><label>اسم المرحلة<input name="name" required placeholder="مثال: المسار الدولي" /></label><label>الرمز<input name="code" required /></label><button className="primary">إضافة مرحلة</button></form><NameList title="المراحل" items={stages} resource="stages" schoolId={schoolId} reload={() => load(schoolId)} /></article>
      <article className="form-card"><h2>الصفوف</h2><form onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); submit("grades", { stage_id: field(f,"stage"), name_ar: field(f,"name"), order: grades.filter(g => g.stage_id === field(f,"stage")).length }, e.currentTarget); }}><label>المرحلة<select name="stage">{stages.map(x => <option value={x.id} key={x.id}>{String(x.name_ar)}</option>)}</select></label><label>اسم الصف<input name="name" required /></label><button className="primary" disabled={!stages.length}>إضافة صف</button></form><NameList title="الصفوف" items={grades} resource="grades" schoolId={schoolId} reload={() => load(schoolId)} /></article>
      <article className="form-card"><h2>الشُعب</h2><form onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); submit("sections", { grade_id: field(f,"grade"), name_ar: field(f,"name"), capacity: Number(field(f,"capacity")) || null }, e.currentTarget); }}><label>الصف<select name="grade">{grades.map(x => <option value={x.id} key={x.id}>{String(x.name_ar)}</option>)}</select></label><div className="two-fields"><label>اسم الشعبة<input name="name" required /></label><label>السعة<input name="capacity" type="number" min="1" /></label></div><button className="primary" disabled={!grades.length}>إضافة شعبة</button></form><NameList title="الشُعب" items={sections} resource="sections" schoolId={schoolId} reload={() => load(schoolId)} /></article>
    </div>}
  </section>;
}
