"use client";

import { FormEvent } from "react";
import type { Item } from "@/lib/setup-api";

export type SetupResource = "years" | "terms" | "shifts" | "patterns" | "days" | "blocks" | "stages" | "grades" | "sections";
type Lists = Record<"years" | "shifts" | "patterns" | "days" | "stages" | "grades", Item[]>;
const weekdays = ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"];
const labels: Record<SetupResource, string> = { years: "العام الدراسي", terms: "الفصل الدراسي", shifts: "الفترة", patterns: "نمط الأسبوع", days: "يوم الدراسة", blocks: "عنصر اليوم", stages: "المرحلة", grades: "الصف", sections: "الشعبة" };
const value = (item: Item, key: string) => String(item[key] ?? "");

export function SetupEditDialog({ resource, item, lists, busy, onClose, onSave }: { resource: SetupResource; item: Item; lists: Lists; busy: boolean; onClose: () => void; onSave: (payload: object) => Promise<void> }) {
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); const get = (key: string) => String(form.get(key) ?? "");
    const payloads: Record<SetupResource, object> = {
      years: { name: get("name"), starts_on: get("starts_on"), ends_on: get("ends_on"), is_current: form.get("is_current") === "on" },
      terms: { academic_year_id: get("academic_year_id"), name_ar: get("name_ar"), name_en: get("name_en") || null, order: Number(get("order")), starts_on: get("starts_on"), ends_on: get("ends_on") },
      shifts: { code: get("code"), name_ar: get("name_ar"), name_en: get("name_en") || null, order: Number(get("order")), is_active: form.get("is_active") === "on" },
      patterns: { code: get("code"), name_ar: get("name_ar"), cycle_week_index: Number(get("cycle_week_index")) },
      days: { shift_id: get("shift_id"), week_pattern_id: get("week_pattern_id"), weekday_index: Number(get("weekday_index")), enabled: form.get("enabled") === "on", label_ar: get("label_ar") || null },
      blocks: { school_day_id: get("school_day_id"), block_order: Number(get("block_order")), block_type: get("block_type"), period_number: get("block_type") === "lesson" ? Number(get("period_number")) : null, label_ar: get("label_ar") || null, starts_at: get("starts_at"), ends_at: get("ends_at"), attendance_mode: get("attendance_mode") },
      stages: { code: get("code"), name_ar: get("name_ar"), order: Number(get("order")) },
      grades: { stage_id: get("stage_id"), name_ar: get("name_ar"), order: Number(get("order")) },
      sections: { grade_id: get("grade_id"), name_ar: get("name_ar"), capacity: get("capacity") ? Number(get("capacity")) : null },
    };
    await onSave(payloads[resource]);
  }
  return <div className="dialog-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><section className="edit-dialog" role="dialog" aria-modal="true" aria-labelledby="edit-title"><div className="dialog-heading"><div><span>تعديل البيانات</span><h2 id="edit-title">{labels[resource]}</h2></div><button type="button" onClick={onClose} aria-label="إغلاق">×</button></div><form onSubmit={submit}>
    {resource === "years" && <><label>اسم العام<input name="name" defaultValue={value(item,"name")} required /></label><div className="two-fields"><label>البداية<input type="date" name="starts_on" defaultValue={value(item,"starts_on")} required /></label><label>النهاية<input type="date" name="ends_on" defaultValue={value(item,"ends_on")} required /></label></div><label className="check-field"><input type="checkbox" name="is_current" defaultChecked={Boolean(item.is_current)} /> العام الدراسي الحالي</label></>}
    {resource === "terms" && <><label>العام<select name="academic_year_id" defaultValue={value(item,"academic_year_id")}>{lists.years.map(x=><option key={x.id} value={x.id}>{value(x,"name")}</option>)}</select></label><div className="two-fields"><label>الاسم العربي<input name="name_ar" defaultValue={value(item,"name_ar")} required /></label><label>الاسم الإنجليزي<input name="name_en" defaultValue={value(item,"name_en")} /></label></div><label>الترتيب<input type="number" min="1" name="order" defaultValue={value(item,"order")} required /></label><div className="two-fields"><label>البداية<input type="date" name="starts_on" defaultValue={value(item,"starts_on")} required /></label><label>النهاية<input type="date" name="ends_on" defaultValue={value(item,"ends_on")} required /></label></div></>}
    {resource === "shifts" && <><div className="two-fields"><label>المسمى<input name="name_ar" defaultValue={value(item,"name_ar")} required /></label><label>الرمز<input name="code" defaultValue={value(item,"code")} required /></label></div><label>الاسم الإنجليزي<input name="name_en" defaultValue={value(item,"name_en")} /></label><label>الترتيب<input type="number" min="0" name="order" defaultValue={value(item,"order")} /></label><label className="check-field"><input type="checkbox" name="is_active" defaultChecked={Boolean(item.is_active)} /> الفترة مفعلة</label></>}
    {resource === "patterns" && <><label>المسمى<input name="name_ar" defaultValue={value(item,"name_ar")} required /></label><div className="two-fields"><label>الرمز<input name="code" defaultValue={value(item,"code")} required /></label><label>فهرس الدورة<input type="number" min="0" name="cycle_week_index" defaultValue={value(item,"cycle_week_index")} required /></label></div></>}
    {resource === "days" && <><label>الفترة<select name="shift_id" defaultValue={value(item,"shift_id")}>{lists.shifts.map(x=><option key={x.id} value={x.id}>{value(x,"name_ar")}</option>)}</select></label><label>نمط الأسبوع<select name="week_pattern_id" defaultValue={value(item,"week_pattern_id")}>{lists.patterns.map(x=><option key={x.id} value={x.id}>{value(x,"name_ar")}</option>)}</select></label><label>اليوم<select name="weekday_index" defaultValue={value(item,"weekday_index")}>{weekdays.map((x,i)=><option key={x} value={i}>{x}</option>)}</select></label><label>المسمى الظاهر<input name="label_ar" defaultValue={value(item,"label_ar")} /></label><label className="check-field"><input type="checkbox" name="enabled" defaultChecked={Boolean(item.enabled)} /> يوم مفعّل</label></>}
    {resource === "blocks" && <><label>اليوم<select name="school_day_id" defaultValue={value(item,"school_day_id")}>{lists.days.map(x=><option key={x.id} value={x.id}>{weekdays[Number(x.weekday_index)]}</option>)}</select></label><div className="two-fields"><label>النوع<select name="block_type" defaultValue={value(item,"block_type")}><option value="lesson">حصة</option><option value="assembly">طابور</option><option value="break">فسحة</option><option value="prayer">صلاة</option><option value="activity">نشاط</option><option value="custom">فترة مخصصة</option></select></label><label>المسمى<input name="label_ar" defaultValue={value(item,"label_ar")} /></label></div><div className="three-fields"><label>من<input type="time" name="starts_at" defaultValue={value(item,"starts_at").slice(0,5)} required /></label><label>إلى<input type="time" name="ends_at" defaultValue={value(item,"ends_at").slice(0,5)} required /></label><label>رقم الحصة<input type="number" min="1" name="period_number" defaultValue={value(item,"period_number")} /></label></div><div className="two-fields"><label>الترتيب<input type="number" min="0" name="block_order" defaultValue={value(item,"block_order")} /></label><label>الحضور<select name="attendance_mode" defaultValue={value(item,"attendance_mode")}><option value="onsite">حضوري</option><option value="remote">عن بعد</option><option value="hybrid">هجين</option></select></label></div></>}
    {resource === "stages" && <><label>المسمى<input name="name_ar" defaultValue={value(item,"name_ar")} required /></label><div className="two-fields"><label>الرمز<input name="code" defaultValue={value(item,"code")} required /></label><label>الترتيب<input type="number" min="0" name="order" defaultValue={value(item,"order")} /></label></div></>}
    {resource === "grades" && <><label>المرحلة<select name="stage_id" defaultValue={value(item,"stage_id")}>{lists.stages.map(x=><option key={x.id} value={x.id}>{value(x,"name_ar")}</option>)}</select></label><label>اسم الصف<input name="name_ar" defaultValue={value(item,"name_ar")} required /></label><label>الترتيب<input type="number" min="0" name="order" defaultValue={value(item,"order")} /></label></>}
    {resource === "sections" && <><label>الصف<select name="grade_id" defaultValue={value(item,"grade_id")}>{lists.grades.map(x=><option key={x.id} value={x.id}>{value(x,"name_ar")}</option>)}</select></label><div className="two-fields"><label>اسم الشعبة<input name="name_ar" defaultValue={value(item,"name_ar")} required /></label><label>السعة<input type="number" min="1" name="capacity" defaultValue={value(item,"capacity")} /></label></div></>}
    <div className="dialog-actions"><button type="button" className="secondary" onClick={onClose}>إلغاء</button><button className="primary" disabled={busy}>{busy ? "جارٍ الحفظ…" : "حفظ التعديلات"}</button></div>
  </form></section></div>;
}
