import { cleanup,fireEvent,render,screen,waitFor } from "@testing-library/react";
import { afterEach,beforeEach,describe,expect,it,vi } from "vitest";
import { masterApi } from "@/lib/master-api";
import { TeachersWorkspace } from "./teachers-workspace";

const snapshot={school:{id:"s1",name_ar:"مدرسة النور",code:"S1"},teachers:[{teacher:{id:"t1",canonical_code:"T-1",name_ar:"أحمد العتيبي",specialty_reference:"الرياضيات",base_workload:18,teaching_workload_limit:24,is_active:true},membership:{id:"m1",school_id:"s1",local_employee_code:"L1",is_home_school:false,is_active:true},schools:[{school_id:"s1",name_ar:"مدرسة النور",code:"S1",is_home_school:false,is_active:true,local_employee_code:"L1",is_current_school:true},{school_id:"s2",name_ar:"مدرسة الفجر",code:"S2",is_home_school:true,is_active:true,local_employee_code:"L2",is_current_school:false}],is_shared:true,assigned_workload:0}],available_teachers:[{id:"t2",canonical_code:"T-2",name_ar:"سارة"}]};
vi.mock("@/lib/master-api",()=>({masterApi:{teachers:vi.fn(),createTeacher:vi.fn(),linkTeacher:vi.fn(),updateTeacher:vi.fn(),updateMembership:vi.fn(),unlink:vi.fn()}}));

describe("teachers workspace",()=>{beforeEach(()=>{Object.defineProperty(window,"localStorage",{configurable:true,value:{getItem:()=>"s1"}});vi.mocked(masterApi.teachers).mockResolvedValue(snapshot)});afterEach(cleanup);
 it("searches the selected school list and shows shared schools",async()=>{render(<TeachersWorkspace/>);expect(await screen.findByText("أحمد العتيبي")).toBeInTheDocument();expect(screen.getByText("معلم مشترك")).toBeInTheDocument();expect(screen.getByText(/مدرسة الفجر/)).toBeInTheDocument();fireEvent.change(screen.getByRole("textbox",{name:"بحث في المعلمين"}),{target:{value:"غير موجود"}});expect(screen.getByText("لا توجد نتائج")).toBeInTheDocument()});
 it("separates creating a teacher from linking an existing identity",async()=>{render(<TeachersWorkspace/>);await screen.findByText("أحمد العتيبي");fireEvent.click(screen.getByRole("button",{name:"إضافة معلم"}));expect(screen.getByRole("dialog")).toHaveTextContent("إضافة معلم جديد");fireEvent.click(screen.getByRole("button",{name:"إغلاق"}));fireEvent.click(screen.getByRole("button",{name:"ربط معلم موجود"}));expect(screen.getByRole("dialog")).toHaveTextContent("سارة")});
 it("provides canonical and school-membership edit flows plus in-app unlink confirmation",async()=>{render(<TeachersWorkspace/>);await screen.findByText("أحمد العتيبي");fireEvent.click(screen.getByRole("button",{name:"تعديل المعلم"}));expect(screen.getByRole("dialog")).toHaveTextContent("تعديل بيانات المعلم");fireEvent.click(screen.getByRole("button",{name:"إغلاق"}));fireEvent.click(screen.getByRole("button",{name:"بيانات المدرسة"}));expect(screen.getByRole("dialog")).toHaveTextContent("هذه المدرسة الأساسية");fireEvent.click(screen.getByRole("button",{name:"إغلاق"}));fireEvent.click(screen.getByRole("button",{name:"فك الارتباط"}));expect(screen.getByRole("alertdialog")).toHaveTextContent("ستبقى هويته ومدارسه الأخرى")});
 it("shows the real home school even when another school is current",async()=>{render(<TeachersWorkspace/>);await screen.findByText("أحمد العتيبي");expect(screen.getByText("مدرسة الفجر · المدرسة الأساسية")).toBeInTheDocument();expect(screen.getByText("مدرسة النور · المدرسة الحالية")).toBeInTheDocument()});
 it("shows an inactive membership and reactivates the same membership",async()=>{const inactive={...snapshot,teachers:[{...snapshot.teachers[0],membership:{...snapshot.teachers[0].membership,is_active:false},schools:snapshot.teachers[0].schools.map(s=>s.school_id==="s1"?{...s,is_active:false}:s),is_shared:false}],available_teachers:[]};vi.mocked(masterApi.teachers).mockResolvedValue(inactive);vi.mocked(masterApi.updateMembership).mockResolvedValue({id:"m1"});render(<TeachersWorkspace/>);expect(await screen.findByText("غير نشط في هذه المدرسة")).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"إعادة التفعيل"}));await waitFor(()=>expect(masterApi.updateMembership).toHaveBeenCalledWith("s1","m1",expect.objectContaining({is_active:true}))) });
 it("preserves zero workload values in the edit form and payload",async()=>{const zero={...snapshot,teachers:[{...snapshot.teachers[0],teacher:{...snapshot.teachers[0].teacher,base_workload:0,teaching_workload_limit:0}}]};vi.mocked(masterApi.teachers).mockResolvedValue(zero);vi.mocked(masterApi.updateTeacher).mockResolvedValue({id:"t1"});render(<TeachersWorkspace/>);await screen.findByText("أحمد العتيبي");fireEvent.click(screen.getByRole("button",{name:"تعديل المعلم"}));expect(screen.getByRole("spinbutton",{name:"النصاب الأساسي"})).toHaveValue(0);expect(screen.getByRole("spinbutton",{name:"حد التدريس"})).toHaveValue(0);fireEvent.click(screen.getByRole("button",{name:"حفظ"}));await waitFor(()=>expect(masterApi.updateTeacher).toHaveBeenCalledWith("s1","t1",expect.objectContaining({base_workload:0,teaching_workload_limit:0}))) });
});
