"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { masterApi, type TeacherCard, type TeacherSnapshot } from "@/lib/master-api";

type Mode = "create" | "link" | "teacher" | "membership";
const val = (value: unknown) => String(value ?? "");

export function TeachersWorkspace() {
  const [schoolId,setSchoolId]=useState(""); const [data,setData]=useState<TeacherSnapshot|null>(null); const [loading,setLoading]=useState(true);
  const [search,setSearch]=useState(""); const [mode,setMode]=useState<Mode|null>(null); const [selected,setSelected]=useState<TeacherCard|null>(null);
  const [removing,setRemoving]=useState<TeacherCard|null>(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const load=useCallback(async(id?:string)=>{const school=id??localStorage.getItem("pm-school")??"";if(!school){setLoading(false);return}setSchoolId(school);setLoading(true);try{setData(await masterApi.teachers(school));setError("")}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);const handler=(e:Event)=>void load((e as CustomEvent<string>).detail);window.addEventListener("pm-school-change",handler);return()=>{clearTimeout(timer);window.removeEventListener("pm-school-change",handler)}},[load]);
  const filtered=useMemo(()=>data?.teachers.filter(card=>[card.teacher.name_ar,card.teacher.canonical_code,card.teacher.specialty_reference,card.membership.local_employee_code].some(x=>val(x).toLowerCase().includes(search.toLowerCase())))??[],[data,search]);
  function open(next:Mode,card?:TeacherCard){setSelected(card??null);setMode(next);setError("")}
  async function reactivate(card:TeacherCard){setBusy(true);setError("");try{await masterApi.updateMembership(schoolId,card.membership.id,{local_employee_code:card.membership.local_employee_code??null,is_home_school:Boolean(card.membership.is_home_school),is_active:true});setMessage("تمت إعادة تفعيل المعلم في هذه المدرسة");await load(schoolId)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),get=(k:string)=>val(f.get(k));setBusy(true);setError("");try{
    if(mode==="create")await masterApi.createTeacher(schoolId,{canonical_code:get("canonical_code"),name_ar:get("name_ar"),name_en:get("name_en")||null,specialty_reference:get("specialty")||null,base_workload:Number(get("base")),teaching_workload_limit:Number(get("limit")),is_active:true,local_employee_code:get("local_code")||null,is_home_school:f.get("home")==="on"});
    if(mode==="link")await masterApi.linkTeacher(schoolId,{teacher_id:get("teacher_id"),local_employee_code:get("local_code")||null,is_home_school:f.get("home")==="on",is_active:true});
    if(mode==="teacher"&&selected)await masterApi.updateTeacher(schoolId,selected.teacher.id,{canonical_code:get("canonical_code"),name_ar:get("name_ar"),name_en:get("name_en")||null,specialty_reference:get("specialty")||null,base_workload:Number(get("base")),teaching_workload_limit:Number(get("limit")),is_active:f.get("active")==="on"});
    if(mode==="membership"&&selected)await masterApi.updateMembership(schoolId,selected.membership.id,{local_employee_code:get("local_code")||null,is_home_school:f.get("home")==="on",is_active:f.get("active")==="on"});
    setMode(null);setMessage("تم حفظ بيانات المعلم");await load(schoolId);
  }catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  if(loading)return <section className="content"><div className="skeleton" aria-label="جار تحميل المعلمين"/></section>;
  return <section className="content master-page"><div className="page-heading"><div><span className="eyebrow">{data?.school.name_ar}</span><h1>المعلمون</h1><p>هوية واحدة للمعلم، حتى عندما يعمل في أكثر من مدرسة.</p></div><div className="heading-actions"><button className="secondary" onClick={()=>open("link")} disabled={!data?.available_teachers.length}>ربط معلم موجود</button><button className="primary" onClick={()=>open("create")}>إضافة معلم</button></div></div>
    {message&&<div className="success-banner" role="status">✓ {message}</div>}{error&&<div className="error-banner" role="alert">{error}</div>}
    <div className="toolbar"><label>بحث في المعلمين<input aria-label="بحث في المعلمين" value={search} onChange={e=>setSearch(e.target.value)} placeholder="الاسم أو الكود أو التخصص"/></label><span>{filtered.length} معلم</span></div>
    {filtered.length===0?<div className="empty-state"><h2>{search?"لا توجد نتائج":"لم تتم إضافة معلمين"}</h2><p>{search?"جرّب كلمة بحث أخرى.":"أضف معلمًا جديدًا أو اربط معلمًا من مدارس الحساب."}</p></div>:<div className="teacher-grid">{filtered.map(card=><article className={`teacher-card${card.membership.is_active?"":" inactive-card"}`} key={card.membership.id}><div className="teacher-title"><div className="avatar">{val(card.teacher.name_ar).slice(0,2)}</div><div><h2>{val(card.teacher.name_ar)}</h2><p>{val(card.teacher.canonical_code)} · {val(card.teacher.specialty_reference)||"دون تخصص مرجعي"}</p></div>{card.is_shared&&<b className="shared-badge">معلم مشترك</b>}{!card.membership.is_active&&<b className="inactive-badge">غير نشط في هذه المدرسة</b>}{!card.teacher.is_active&&<b className="inactive-badge">هوية المعلم مؤرشفة</b>}</div><div className="workload-row"><div><span>النصاب الأساسي</span><strong>{val(card.teacher.base_workload)}</strong></div><div><span>حد التدريس</span><strong>{val(card.teacher.teaching_workload_limit)}</strong></div><div><span>المسند حاليًا</span><strong>{card.assigned_workload}</strong><small>من بيانات الإسناد الفعلية</small></div></div><div className="school-links"><span>مدارسه</span>{card.schools.map(s=><b key={s.school_id}>{s.name_ar}{s.is_home_school&&s.is_active?" · المدرسة الأساسية":""}{s.is_current_school?" · المدرسة الحالية":""}{!s.is_active?" · غير نشط":""}</b>)}</div><div className="card-actions"><button onClick={()=>open("teacher",card)}>{card.teacher.is_active?"تعديل المعلم":"إعادة تفعيل المعلم"}</button>{!card.membership.is_active&&card.teacher.is_active&&<button className="primary" disabled={busy} onClick={()=>void reactivate(card)}>إعادة التفعيل</button>}<button onClick={()=>open("membership",card)}>بيانات المدرسة</button><button className="danger-link" onClick={()=>setRemoving(card)}>فك الارتباط</button></div></article>)}</div>}
    {mode&&<div className="dialog-backdrop"><section className="edit-dialog" role="dialog" aria-modal="true" aria-labelledby="teacher-dialog"><div className="dialog-heading"><div><span>بيانات المعلمين</span><h2 id="teacher-dialog">{mode==="create"?"إضافة معلم جديد":mode==="link"?"ربط معلم موجود":mode==="teacher"?"تعديل بيانات المعلم":"تعديل بيانات المدرسة"}</h2></div><button onClick={()=>setMode(null)} aria-label="إغلاق">×</button></div><form onSubmit={submit}>
      {mode==="link"?<label>المعلم<select name="teacher_id" required>{data?.available_teachers.map(t=><option key={t.id} value={t.id}>{val(t.name_ar)} — {val(t.canonical_code)}</option>)}</select></label>:mode!=="membership"&&<><div className="two-fields"><label>اسم المعلم<input name="name_ar" defaultValue={val(selected?.teacher.name_ar)} required/></label><label>الاسم الإنجليزي<input name="name_en" defaultValue={val(selected?.teacher.name_en)}/></label></div><div className="two-fields"><label>الكود الموحد<input name="canonical_code" defaultValue={val(selected?.teacher.canonical_code)} required/></label><label>التخصص (مرجع فقط)<input name="specialty" defaultValue={val(selected?.teacher.specialty_reference)}/></label></div><div className="two-fields"><label>النصاب الأساسي<input type="number" min="0" name="base" defaultValue={val(selected?.teacher.base_workload??18)} required/></label><label>حد التدريس<input type="number" min="0" name="limit" defaultValue={val(selected?.teacher.teaching_workload_limit??24)} required/></label></div>{mode==="teacher"&&<label className="check-field"><input type="checkbox" name="active" defaultChecked={Boolean(selected?.teacher.is_active)}/> المعلم نشط</label>}</>}
      {(mode==="create"||mode==="link"||mode==="membership")&&<><label>الكود المحلي في المدرسة<input name="local_code" defaultValue={val(selected?.membership.local_employee_code)}/></label><label className="check-field"><input type="checkbox" name="home" defaultChecked={Boolean(selected?.membership.is_home_school)}/> هذه المدرسة الأساسية</label>{mode==="membership"&&<label className="check-field"><input type="checkbox" name="active" defaultChecked={Boolean(selected?.membership.is_active)}/> الارتباط نشط</label>}</>}
      <div className="dialog-actions"><button type="button" className="secondary" onClick={()=>setMode(null)}>إلغاء</button><button className="primary" disabled={busy}>{busy?"جار الحفظ…":"حفظ"}</button></div></form></section></div>}
    {removing&&<div className="dialog-backdrop"><section className="confirm-dialog" role="alertdialog" aria-modal="true"><h2>فك ارتباط المعلم</h2><p>سيُزال المعلم من المدرسة الحالية فقط، وستبقى هويته ومدارسه الأخرى محفوظة.</p><div className="dialog-actions"><button className="secondary" onClick={()=>setRemoving(null)}>إلغاء</button><button className="danger-button" onClick={async()=>{setBusy(true);try{await masterApi.unlink(schoolId,removing.membership.id);setRemoving(null);setMessage("تم فك ارتباط المعلم");await load(schoolId)}catch(e){setError((e as Error).message);setRemoving(null)}finally{setBusy(false)}}}>فك الارتباط</button></div></section></div>}
  </section>;
}
