"use client";

import { useMemo, useState } from "react";
import { projectApi, type AuditEvent, type CandidateDetail, type MoveAnalysis, type ProjectSlot, type RepairPreview, type SnapshotComparison, type TimetableSnapshot, type WorkingTimetable } from "@/lib/project-api";

const days = ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"];
const clock = (n: number) => `${String(Math.floor(n / 60)).padStart(2, "0")}:${String(n % 60).padStart(2, "0")}`;
const labels: Record<string, string> = { teacher_conflict: "المعلم مرتبط بحصة أخرى متداخلة", section_conflict: "الشعبة لديها حصة أخرى متداخلة", exclusive_resource_conflict: "المورد الحصري مستخدم في هذا الوقت", hard_rule_violation: "النقل يخالف قاعدة إلزامية", lock_violation: "الحصة أو المنطقة مقفلة" };
type View = "general" | "section" | "teacher" | "subject" | "resource";

export function TimetableEditor({ projectId, candidate }: { projectId: string; candidate: CandidateDetail }) {
  const [table, setTable] = useState<WorkingTimetable | null>(null);
  const [slots, setSlots] = useState<ProjectSlot[]>([]);
  const [analysis, setAnalysis] = useState<MoveAnalysis | null>(null);
  const [repair, setRepair] = useState<RepairPreview | null>(null);
  const [snapshots, setSnapshots] = useState<TimetableSnapshot[]>([]);
  const [audit, setAudit] = useState<AuditEvent[]>([]); const [comparison, setComparison] = useState<SnapshotComparison | null>(null); const [snapshotName, setSnapshotName] = useState("");
  const [view, setView] = useState<View>("general"); const [filter, setFilter] = useState(""); const [week, setWeek] = useState(0); const [dragged, setDragged] = useState("");
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const fail = (reason: unknown) => setError(reason instanceof Error ? reason.message : "تعذر تنفيذ العملية");

  async function start() { setBusy(true); try { const [working, problem] = await Promise.all([projectApi.deriveWorking(projectId, candidate.id), projectApi.problem(projectId)]); setTable(working); setSlots(problem.slots); setMessage("أصبحت النسخة جاهزة للتحرير الآمن."); } catch (reason) { fail(reason); } finally { setBusy(false); } }
  async function mutate(action: () => Promise<WorkingTimetable>, success: string) { setBusy(true); try { setTable(await action()); setAnalysis(null); setRepair(null); setMessage(success); } catch (reason) { fail(reason); } finally { setBusy(false); } }
  async function analyze(slotId: string, occurrence = dragged) { if (!table || !occurrence) return; setBusy(true); setRepair(null); try { setAnalysis(await projectApi.analyzeMove(projectId, { revision: table.revision, occurrence_id: occurrence, target_slot_id: slotId })); } catch (reason) { fail(reason); } finally { setBusy(false); setDragged(""); } }
  async function previewRepair() { if (!table || !analysis) return; setBusy(true); try { setRepair(await projectApi.repairPreview(projectId, { revision: table.revision, occurrence_id: analysis.occurrence_id, target_slot_id: analysis.target_slot.id, time_limit_seconds: 5 })); } catch (reason) { fail(reason); } finally { setBusy(false); } }
  async function toggleLock(occurrenceId: string) { if (!table) return; const lock = table.locks.find(item => item.occurrence_id === occurrenceId); if (lock) return mutate(() => projectApi.unlock(projectId, lock.id, table.revision), "تم فك قفل الحصة."); setBusy(true); try { await projectApi.lockOccurrence(projectId, occurrenceId, table.revision); setTable(await projectApi.working(projectId)); setMessage("تم قفل الحصة وستحترمها عمليات النقل والإصلاح."); } catch (reason) { fail(reason); } finally { setBusy(false); } }
  async function snapshot() { if (!table || !snapshotName.trim()) return; setBusy(true); try { await projectApi.createSnapshot(projectId, snapshotName.trim(), table.revision); setTable(await projectApi.working(projectId)); setSnapshots(await projectApi.snapshots(projectId)); setSnapshotName(""); setMessage("تم حفظ اللقطة دون تغيير الحصص."); } catch (reason) { fail(reason); } finally { setBusy(false); } }

  const entities = useMemo(() => { if (!table || view === "general") return []; const all = table.entries.flatMap(entry => view === "section" ? entry.sections : view === "teacher" ? entry.teachers : view === "resource" ? entry.resources : [entry.subject]); return [...new Map(all.map(x => [x.id, x])).values()]; }, [table, view]);
  const visible = useMemo(() => (table?.entries ?? []).filter(entry => entry.project_cycle_week_index === week && (!filter || view === "general" || (view === "section" ? entry.sections : view === "teacher" ? entry.teachers : view === "resource" ? entry.resources : [entry.subject]).some(x => x.id === filter))), [table, week, filter, view]);
  const weeks = [...new Set(slots.map(x => x.project_cycle_week_index))]; const weekSlots = slots.filter(x => x.project_cycle_week_index === week);

  if (!table) return <section className="editor-launch"><div><p className="eyebrow">محرر احترافي</p><h3>حرّر هذا البديل بأمان</h3><p>يبقى بديل CP-SAT الأصلي ثابتًا، وتُنشأ نسخة عمل مستقلة قابلة للتراجع.</p></div><button className="primary" disabled={busy} onClick={() => void start()}>{busy ? "جارٍ التحضير…" : "فتح محرر الجدول"}</button></section>;
  return <section className="professional-editor" aria-label="محرر الجدول الاحترافي">
    <header className="editor-header"><div><p className="eyebrow">نسخة العمل {table.version_number} · مراجعة {table.revision}</p><h2>محرر الجدول الاحترافي</h2><p>{table.change_summary}</p></div><div className="editor-actions"><button disabled={!table.can_undo || busy} onClick={() => void mutate(() => projectApi.undo(projectId, table.revision), "تم التراجع وحفظه في السجل.")}>↶ تراجع</button><button disabled={!table.can_redo || busy} onClick={() => void mutate(() => projectApi.redo(projectId, table.revision), "تمت إعادة العملية.")}>↷ إعادة</button><button onClick={() => void projectApi.audit(projectId).then(setAudit).catch(fail)}>سجل التعديلات</button></div></header>
    {message && <p className="success-banner" role="status">{message}</p>}{error && <p className="error-banner" role="alert">{error}<button aria-label="إغلاق" onClick={() => setError("")}>×</button></p>}
    <div className="editor-toolbar"><div className="segmented" aria-label="طريقة العرض">{([['general','الجدول العام'],['section','الشعبة'],['teacher','المعلم'],['subject','المادة'],['resource','الغرفة / المورد']] as [View,string][]).map(([key,label]) => <button key={key} className={view === key ? "selected" : ""} onClick={() => { setView(key); setFilter(""); }}>{label}</button>)}</div>{view !== "general" && <label>تصفية حسب<select aria-label="تصفية عرض الجدول" value={filter} onChange={e => setFilter(e.target.value)}><option value="">الكل</option>{entities.map(x => <option key={x.id} value={x.id}>{x.name_ar}</option>)}</select></label>}</div>
    <div className="week-tabs">{weeks.map(x => <button key={x} className={week === x ? "selected" : ""} onClick={() => setWeek(x)}>أسبوع المشروع {x + 1}</button>)}</div><p className="editor-hint">اسحب بطاقة الحصة وأسقطها فوق وقت متاح. يحلل الخادم التعارضات قبل الحفظ.</p>
    <div className="timetable-grid">{days.map((day, index) => <section key={day} className="day-column"><h3>{day}</h3>{weekSlots.filter(x => x.weekday_index === index).sort((a,b) => a.starts_at_minute-b.starts_at_minute).map(slot => { const entry = visible.find(x => x.slot_id === slot.id); return <div key={slot.id} className={`editor-slot ${entry ? "occupied" : "empty"}`} onDragOver={e => e.preventDefault()} onDrop={() => void analyze(slot.id)}><time>{clock(slot.starts_at_minute)}–{clock(slot.ends_at_minute)}</time>{entry ? <article draggable onDragStart={() => setDragged(entry.occurrence_id)}><strong>{entry.subject.name_ar}</strong><span>{entry.sections.map(x => x.name_ar).join(" + ")}</span><span>{entry.teachers.map(x => x.name_ar).join(" + ")}</span><button aria-label={`قفل ${entry.subject.name_ar}`} onClick={e => { e.stopPropagation(); void toggleLock(entry.occurrence_id); }}>{table.locks.some(x => x.occurrence_id === entry.occurrence_id) ? "🔒 فك القفل" : "🔓 قفل"}</button></article> : <span>وقت متاح</span>}</div>; })}</section>)}</div>
    {analysis && <aside className={`conflict-panel ${analysis.valid ? "valid" : "invalid"}`} aria-live="polite"><p className="eyebrow">تحليل النقل من الخادم</p><h3>{analysis.valid ? "النقل آمن" : "يحتاج معالجة قبل الحفظ"}</h3><p>تغير الجزاء المتوقع: {analysis.soft_penalty_delta > 0 ? "+" : ""}{analysis.soft_penalty_delta}</p>{analysis.violations.map((x,i) => <p key={`${x.code}-${i}`}>⚠ {labels[x.code] ?? x.code}</p>)}{analysis.alternative_slots.length > 0 && <div><strong>أوقات بديلة قريبة</strong>{analysis.alternative_slots.map(x => <button key={x.id} onClick={() => void analyze(x.id, analysis.occurrence_id)}>{days[x.weekday_index]} {clock(x.starts_at_minute)}</button>)}</div>}<div className="dialog-actions"><button onClick={() => setAnalysis(null)}>إلغاء</button>{analysis.valid && <button className="primary" onClick={() => void mutate(() => projectApi.applyMove(projectId, { revision: table.revision, occurrence_id: analysis.occurrence_id, target_slot_id: analysis.target_slot.id }), "تم النقل بعد إعادة التحقق.")}>تطبيق النقل</button>}{analysis.swap_candidates.map(x => <button key={x.occurrence_id} onClick={() => void mutate(() => projectApi.applySwap(projectId, { revision: table.revision, first_occurrence_id: analysis.occurrence_id, second_occurrence_id: x.occurrence_id }), "تم التبديل الذري.")}>تبديل مباشر</button>)}{!analysis.valid && <button className="primary" disabled={busy} onClick={() => void previewRepair()}>إصلاح تلقائي بأقل تغييرات</button>}</div></aside>}
    {repair && <aside className="repair-preview"><p className="eyebrow">معاينة فقط — لا توجد أي كتابة في قاعدة البيانات</p><h3>{repair.total_moved_occurrences} تغييرات مقترحة</h3>{repair.changes.map(x => <p key={x.occurrence_id}>{x.from.slot_id} ← {x.to.slot_id}</p>)}<button onClick={() => setRepair(null)}>رفض</button><button className="primary" onClick={() => void mutate(() => projectApi.repairApply(projectId, { revision: table.revision, occurrence_id: repair.occurrence_id, target_slot_id: repair.target_slot_id, changes: repair.changes, fingerprint: repair.fingerprint }), "تم تطبيق حزمة الإصلاح المعتمدة.")}>اعتماد الإصلاح</button></aside>}
    <section className="snapshot-panel"><div className="section-heading"><div><h3>اللقطات والإصدارات</h3><p>الاستعادة تنشئ إصدارًا جديدًا ولا تمحو التاريخ.</p></div><button onClick={() => void projectApi.snapshots(projectId).then(setSnapshots).catch(fail)}>عرض اللقطات</button></div><div className="snapshot-create"><input aria-label="اسم اللقطة" value={snapshotName} onChange={e => setSnapshotName(e.target.value)} placeholder="مثال: قبل تعديلات يوم الأحد"/><button disabled={!snapshotName.trim() || busy} onClick={() => void snapshot()}>حفظ لقطة مسماة</button></div>{snapshots.map(x => <article key={x.id}><div><strong>{x.name}</strong><span>{x.changed_occurrences} حصة مختلفة</span></div><div><button onClick={() => void projectApi.compareSnapshot(projectId, x.id).then(setComparison).catch(fail)}>مقارنة</button><button onClick={() => void mutate(() => projectApi.restoreSnapshot(projectId, x.id, table.revision), "تمت الاستعادة في إصدار جديد.")}>استعادة كإصدار جديد</button></div></article>)}</section>
    {comparison && <aside className="comparison-panel"><h3>مقارنة اللقطة: {comparison.changed_occurrences} حصة متغيرة</h3>{comparison.changes.map(x => <p key={x.occurrence_id}>{x.occurrence_id}: {x.snapshot.slot_id} ← {x.current?.slot_id ?? "محذوفة"}</p>)}</aside>}
    {audit.length > 0 && <section className="audit-panel"><h3>سجل التعديلات</h3>{audit.map(x => <article key={x.id}><strong>{x.summary}</strong><span>مراجعة {x.revision} · {new Date(x.created_at).toLocaleString("ar-SA")}</span></article>)}</section>}
  </section>;
}
